Fix crash when access bookmarked accounts - Closes #2981
LiskHQ/lisk-desktop pull request #3019
Opened 2020-08-19 12:02 UTC by isalga

### What was the problem?
This PR resolves #2981 
When accessing a bookmarked regular(non delegate) account, from a previous bookmarked delegate account, the view 
was trying to render the delegate tab but as the account was not delegate the code was crashing when accessing `delegate.data.username` at `delegateProfile.js` because data property was `undefined`.

### How was it solved?
Prevent `delegate.data` from being `undefined` setting an empty object.

### How was it tested?
Opening bookmark menu and then open a delegate account, after that repeat the same process but opening a regular account. Repeat that alternating from delegate-to-regular and regular-to-delegate.

2020-08-19 14:06 UTC, sridharmeganathan submitted a review, later dismissed
Great job. Working as expected

2020-08-20 14:31 UTC, UsamaHameed requested changes

2020-08-20 14:31 UTC, UsamaHameed commented on src/components/screens/wallet/delegateProfile/index.js
> +const delegateProfile = ({
Can you please move this component into its own file and export the component with the `withTransaction` HOC from the index file?

2020-08-24 07:00 UTC, UsamaHameed approved these changes

2020-08-24 07:00 UTC, merged