Remove votes screen - Closes #3053
LiskHQ/lisk-desktop pull request #3055
Opened 2020-09-09 11:32 UTC by reyraa

### What was the problem?
This PR resolves #3053

### How was it solved?
Removes the screen and all its components.

2020-09-14 09:34 UTC, isalga approved these changes

2020-09-14 13:58 UTC, UsamaHameed requested changes

2020-09-14 13:58 UTC, UsamaHameed commented on src/components/shared/navigationBars/sideBar/index.test.js
>      expect(wrapper).toContainMatchingElements(8, 'a');
We need to change this to 7 as well.

2020-09-16 11:27 UTC, UsamaHameed requested changes

2020-09-16 11:27 UTC, UsamaHameed commented on src/components/toolbox/table/table.test.js
> +      expect(iterationKey.mock.calls.length).toBe(props.data.length);
```suggestion
      expect(iterationKey).toHaveBeenCalledTimes(props.data.length);
```

2020-09-16 11:58 UTC, isalga approved these changes

2020-09-16 13:05 UTC, UsamaHameed approved these changes

2020-09-17 07:28 UTC, UsamaHameed approved these changes

2020-09-17 07:28 UTC, merged