Delegate Profile New Design - Closes @2921
LiskHQ/lisk-desktop pull request #3061
Opened 2020-09-14 07:18 UTC by UsamaHameed

### What was the problem?
This PR resolves #2921

### How was it solved?
Implemented the new design as specified in the prototype

### How was it tested?
WIP

2020-09-15 08:37 UTC, isalga requested changes

2020-09-15 08:37 UTC, isalga commented on src/components/screens/wallet/delegateProfile/delegateProfile.test.js
> +  it.skip('Should render active delegate with passed props', () => {
Why is it skipped?

2020-09-15 08:37 UTC, isalga commented on src/components/screens/wallet/delegateProfile/delegateProfile.test.js
> +  it.skip('Should render inactive delegate', () => {
Same

2020-09-15 08:37 UTC, isalga commented on src/components/screens/wallet/delegateProfile/delegateProfile.css
> +  flex-direction: row !important;
If it is possible I think it would be better to not use !important. Can these styles be done in another way that does not require to use it?

2020-09-15 10:09 UTC, isalga approved these changes

2020-09-28 11:55 UTC, isalga submitted a review, later dismissed

2020-10-07 12:42 UTC, reyraa approved these changes

2020-10-07 12:46 UTC, isalga approved these changes

2020-10-07 13:09 UTC, merged