Missing information in different pages - Closes #3284
LiskHQ/lisk-desktop pull request #3285
Opened 2021-01-18 17:30 UTC by reyraa

### What was the problem?
This PR resolves #3284

### How was it solved?
 - Display `delegate weight` instead of `approval`, since approval is not available anymore.

### How was it tested?
Unit tests

2021-01-19 15:29 UTC, UsamaHameed requested changes

2021-01-19 15:29 UTC, UsamaHameed commented on src/components/screens/monitor/delegates/delegatesTable/delegateWeight.js
> +  const value = val;
Why not name the prop value?

2021-01-19 16:09 UTC, reyraa commented on src/components/screens/monitor/delegates/delegatesTable/delegateWeight.js
> +  const value = val;
This is in progress.

2021-01-21 13:42 UTC, UsamaHameed approved these changes

2021-01-21 13:45 UTC, isalga approved these changes

2021-01-21 13:45 UTC, merged