Fix forging details - Closes #3411
LiskHQ/lisk-desktop pull request #3418
Opened 2021-03-05 11:30 UTC by isalga

### What was the problem?
This PR resolves #3411

### How was it solved?
WIP

### How was it tested?
WIP

2021-03-10 10:53 UTC, sridharmeganathan requested changes
@isalga Forging status and forging time is incorrect. Please fix 

![image](https://user-images.githubusercontent.com/51332105/110618169-c7143580-8196-11eb-9d9c-5cfb9fd0c6d1.png)

2021-03-10 15:55 UTC, isalga commented on src/utils/api/transaction/btc.js
> +      return reject(new Error('Insufficient (estimated) balance'));
DeepScan throws error if we don't

2021-03-11 08:46 UTC, UsamaHameed commented on src/utils/api/transaction/btc.js
> +      return reject(new Error('Insufficient (estimated) balance'));
Please read https://deepscan.io/docs/rules/promise-reject-fall-through and only apply `return` after the `reject` not before. Also, remove the `return`s that you added for consistency; if you have to disable eslint for those lines, please do so.

2021-03-11 12:39 UTC, UsamaHameed approved these changes

2021-03-11 13:39 UTC, sridharmeganathan approved these changes
Forging times calculation should be fixed in SDK 5 changes

2021-03-11 13:40 UTC, merged