Retrieve tx schema - Closes #3432
LiskHQ/lisk-desktop pull request #3458
Opened 2021-03-26 15:15 UTC by isalga

### What was the problem?
This PR resolves #3432

### How was it solved?
WIP

### How was it tested?
WIP

2021-03-30 10:21 UTC, UsamaHameed requested changes

2021-03-30 10:21 UTC, UsamaHameed commented on src/app/index.js
> +      selectSchema(id, network);
Please rename to something more appropriate like `retrieveSchemas` and do `Object.values(...)...` inside that function.

2021-03-30 10:21 UTC, UsamaHameed commented on src/app/index.js
> +  const network = useSelector(state => state.network);
Please add a selector for service url instead. `useSelector(selectServiceUrl)`

2021-03-30 10:21 UTC, UsamaHameed commented on src/utils/api/transaction/lsk.js
> +    selectSchema(moduleAssetType, network)
This function should stay the same.

2021-03-30 10:21 UTC, UsamaHameed commented on src/utils/api/transaction/lsk.js
> +  const schema = await selectSchema(moduleAssetType, network);
This function should stay the same.

2021-03-31 08:09 UTC, UsamaHameed requested changes

2021-03-31 08:09 UTC, UsamaHameed commented on src/utils/moduleAssets.js
> +  Object.values(MODULE_ASSETS_NAME_ID_MAP).forEach(async (moduleAssetId) => {
I don't think we need to make several requests. If I remember correctly, you can make the request without any parameters and it should return all the schemas (which is fine for our case).

2021-03-31 09:17 UTC, UsamaHameed approved these changes

2021-03-31 09:47 UTC, reyraa approved these changes

2021-03-31 09:48 UTC, merged