Fix transaction broadcast - Closes #3459, #3467
LiskHQ/lisk-desktop pull request #3468
Opened 2021-04-07 11:43 UTC by UsamaHameed

### What was the problem?
This PR resolves #3459, #3467

### How was it solved?

### How was it tested?

2021-04-08 11:21 UTC, reyraa requested changes

2021-04-08 11:21 UTC, reyraa commented on src/utils/account.js
>    return undefined;
These retuened `undefined` are essentially silent failures. I think we should add a logger here so we don't overlook the broken features.

2021-04-08 11:21 UTC, reyraa commented on src/utils/account.js
>    return undefined;
Same goes for the other two convertors.

2021-04-08 11:21 UTC, reyraa commented on src/utils/api/account/lsk.js
> +  console.log({ params, normParams });
Remove?

2021-04-08 11:21 UTC, reyraa commented on src/utils/api/transaction/lsk.js
> +import { extractAddressFromPublicKey } from '../../account';
Should we use aliases here?

2021-04-08 11:21 UTC, reyraa commented on src/utils/api/transaction/lsk.js
> +  console.log(transaction);
Don't forget to remove this.

2021-04-08 11:21 UTC, reyraa commented on src/utils/api/transaction/lsk.js
>    if (moduleAssetId === MODULE_ASSETS_NAME_ID_MAP.transfer) {
A switch-case seems more readable here.

2021-04-08 11:21 UTC, reyraa commented on src/utils/api/transaction/lsk.js
> +    if (moduleAssetId === MODULE_ASSETS_NAME_ID_MAP.transfer) {
A switch-case seems more readable here.

2021-04-09 07:59 UTC, UsamaHameed commented on src/utils/api/transaction/lsk.js
> +import { extractAddressFromPublicKey } from '../../account';
Already done in the next PR.

2021-04-09 08:00 UTC, UsamaHameed commented on src/utils/api/transaction/lsk.js
> +    if (moduleAssetId === MODULE_ASSETS_NAME_ID_MAP.transfer) {
Taken care of in the next PR.

2021-04-09 09:46 UTC, reyraa approved these changes

2021-04-09 09:47 UTC, merged