Display a warning message when user sends the entire balance - Closes #3366
LiskHQ/lisk-desktop pull request #3729
Opened 2021-08-13 10:31 UTC by isalga

### What was the problem?
This PR resolves #3366

### How was it solved?

### How was it tested?

2021-08-16 15:56 UTC, MichalTuleja requested changes
The behaviour of that message box is correct, but not very intuitive:
- Making that message disappear also makes the amount disappear
- Changing the amount to lower value does not cause the message disappear

Is it possible to track the amount and display the message based on that input?

2021-08-16 18:10 UTC, sridharmeganathan submitted a review, later dismissed

2021-08-17 14:08 UTC, sridharmeganathan approved these changes

2021-08-17 14:25 UTC, MichalTuleja approved these changes
Looks good 👍  Thanks @isalga

2021-08-17 14:26 UTC, merged