Update domain lisk.io to lisk.com - Closes #3815
LiskHQ/lisk-desktop pull request #3817
Opened 2021-09-27 20:54 UTC by ManuGowda

### What was the problem?

This PR resolves #3815

### How was it solved?

- Updated domain reference from `io` to `com`
- Updated Lisk explorer reference to community explorer

### How was it tested?

- Navigate to all links
- Build and run the app to see if the app works

2021-09-28 18:28 UTC, ikem-legend submitted a review, later dismissed

2021-09-29 10:31 UTC, reyraa submitted a review, later dismissed

2021-09-29 12:14 UTC, fchavant requested changes

2021-09-29 12:14 UTC, fchavant commented on app/package.json
> +    "email": "admin@lisk.com"
This email adress/alias does not exist.

2021-09-29 12:14 UTC, fchavant commented on docs/DEVELOPMENT_GUIDE.md
> +[info@lisk.com](mailto:info@lisk.com).
As far as I can tell neither info@lisk.io nor info@lisk.com exist.

2021-09-29 12:14 UTC, fchavant commented on package.json
> +  "author": "Lisk Foundation <admin@lisk.com>, lightcurve GmbH <admin@lightcurve.io>",
Same as above.

2021-09-29 12:14 UTC, fchavant commented on src/components/shared/errorBoundary/index.js
> +      const recipient = 'hubdev@lisk.com';
Neither hubdev@lisk.io nor hubdev@lisk.com exist.

2021-09-29 12:14 UTC, fchavant commented on src/components/screens/login/networkSelector/networkSelector.js
> +                      placeholder="e.g. https://mainnet-service.lisk.com or 192.168.0.1:4000"
Why use mainnet-service.lisk.com here but service.lisk.com above and below? That seems inconsistent.

2021-09-29 12:14 UTC, fchavant commented on src/constants/piwik.js
> +  URL: 'https://matomo.lisk.com',
matomo.lisk.com does not exist

2021-09-29 12:14 UTC, fchavant commented on src/utils/helpers.js
> +  const recipient = 'hubdev@lisk.com';
Same as above.

2021-09-30 06:36 UTC, reyraa approved these changes

2021-09-30 08:22 UTC, ikem-legend approved these changes

2021-09-30 09:02 UTC, merged