Unable to Sign multisignature transaction - Closes #3975
LiskHQ/lisk-desktop pull request #3987
Opened 2021-12-01 08:37 UTC by reyraa

### What was the problem?

This PR resolves #3975

### How was it solved?

### How was it tested?

2021-12-01 23:40 UTC, isalga requested changes

2021-12-01 23:40 UTC, isalga commented on src/components/screens/signMultiSignTransaction/summary/summary.js
> +    title: signatureStatus === 'fullySigned' ? t('Continue') : t('Sign'),
```suggestion
    title: signatureStatus === signatureCollectionStatus.fullySigned ? t('Continue') : t('Sign'),
```

2021-12-01 23:40 UTC, isalga commented on src/components/screens/signMultiSignTransaction/summary/summary.js
> +  const showFeedback = !isMember || signatureStatus === 'fullySigned' || signatureStatus === 'occupiedByOptionals';
```suggestion
  const showFeedback = !isMember || signatureStatus === signatureCollectionStatus.fullySigned || signatureStatus === signatureCollectionStatus.occupiedByOptionals;
```

2021-12-01 23:40 UTC, isalga commented on src/components/screens/signMultiSignTransaction/summary/footer.js
> +      <div className={`${styles.feedback} ${signatureStatus === 'occupiedByOptionals' ? styles.warning : styles.error} feedback`}>
Prefer to use `signatureCollectionStatus.occupiedByOptionals`
```suggestion
      <div className={`${styles.feedback} ${signatureStatus === signatureCollectionStatus.occupiedByOptionals ? styles.warning : styles.error} feedback`}>
```

2021-12-02 11:00 UTC, ikem-legend approved these changes

2021-12-02 12:18 UTC, gadjacobs approved these changes

2021-12-03 08:31 UTC, merged