Fix negative value in punished delegates warning and forged blocks broken link
LiskHQ/lisk-desktop pull request #3995
Opened 2021-12-03 08:31 UTC by gadjacobs

### What was the problem?

This PR resolves #3974 

### How was it solved?

- Show link only when there's been a forged block
- Check that the number of days left being punished is greater than zero before displaying a warning

### How was it tested?

Visually.

2021-12-03 10:08 UTC, ikem-legend approved these changes
Great job!

2021-12-04 19:28 UTC, reyraa requested changes

2021-12-04 19:28 UTC, reyraa commented on src/components/shared/warnPunishedDelegate/index.js
> +  daysLeft >= 1 ? (
Why mount the component in the first place? If the punishment is already over, the warning component must not be mounted. I think this condition must be moved to the `editVote` and `wallet/overview` components.

2021-12-08 10:04 UTC, reyraa approved these changes

2021-12-08 10:04 UTC, merged