Add ineligible delegates to outside round - Closes #3973
LiskHQ/lisk-desktop pull request #3996
Opened 2021-12-03 11:33 UTC by gadjacobs

### What was the problem?

This PR resolves #3973

### How was it solved?

Adding 'non-eligible' status to the outside round API call.

### How was it tested?

Visually.

2021-12-04 21:42 UTC, reyraa requested changes
Ineligible delegates are added to the list by [this commit](https://github.com/LiskHQ/lisk-desktop/pull/3990/commits/2fbc186442a02cbaaa81c5927d388ffdf2fe891d). We should adapt the title and explain the acceptance criteria accurately. Otherwise it's hard to review. 
I only see indentations changed. What is the logical change applied?

2021-12-07 07:01 UTC, gadjacobs commented on src/components/screens/monitor/delegates/index.js
>              status: 'standby,non-eligible',
@reyraa 'non-eligible' status was added to the API call parameters.

2021-12-07 07:06 UTC, gadjacobs commented
> Ineligible delegates are added to the list by [this commit](https://github.com/LiskHQ/lisk-desktop/pull/3990/commits/2fbc186442a02cbaaa81c5927d388ffdf2fe891d). We should adapt the title and explain the acceptance criteria accurately. Otherwise it's hard to review. I only see indentations changed. What is the logical change applied?

@reyraa I think this issue is a false positive. For some reason [this commit](https://github.com/LiskHQ/lisk-desktop/pull/3990/commits/2fbc186442a02cbaaa81c5927d388ffdf2fe891d) was not merged into release and it fixed the problem in this issue.

2021-12-07 08:24 UTC, reyraa approved these changes

2021-12-07 08:24 UTC, merged