Fix voters filter - Closes #4126
LiskHQ/lisk-desktop pull request #4135
Opened 2022-02-01 14:29 UTC by isalga

### What was the problem?

This PR resolves #4126 

### How was it solved?

- Fix filter function

### How was it tested?

2022-02-01 16:32 UTC, eniolam1000752 requested changes

2022-02-01 16:32 UTC, eniolam1000752 commented on src/components/screens/wallet/delegateProfile/delegateVotesView.js
> +      v => v.username.includes(searchInput) || v.address.includes(searchInput),
if `username` or `address` is undefined then the code breaks just as it did when I checked it against testnet

![image](https://user-images.githubusercontent.com/32064769/152009147-50bca707-b65c-471d-8eb3-86758740c474.png)

```suggestion
      v => (v.username && v.username.includes(searchInput)) || (v.address && v.address.includes(searchInput)),
```

2022-02-01 19:58 UTC, ikem-legend submitted a review, later dismissed

2022-02-02 10:03 UTC, eniolam1000752 submitted a review, later dismissed
LGTM

2022-02-02 10:08 UTC, ikem-legend approved these changes

2022-02-02 12:46 UTC, ManuGowda reviewed
@isalga the PR looks good, to ensure we have no regression in future, can we add tests?

2022-02-02 17:37 UTC, ManuGowda approved these changes
Great job @isalga the tests are 💯 good

2022-02-02 17:40 UTC, eniolam1000752 approved these changes
LGTM

2022-02-02 17:47 UTC, ikem-legend approved these changes

2022-02-02 18:49 UTC, merged