Disable send button for an incorrect second passphrase - Closes #4169
LiskHQ/lisk-desktop pull request #4171
Opened 2022-02-21 14:30 UTC by eniolam1000752

### What was the problem?

This PR resolves #4169 

### How was it solved?

- [x] Disabling send button when there is a validation error on the second passphrase

### How was it tested?

- Try initiating a transition on a multi-signature account by providing a second passphrase
- providing an invalid passphrase disables the send button

2022-02-21 20:00 UTC, ManuGowda approved these changes

2022-02-22 08:13 UTC, reyraa requested changes

2022-02-22 08:13 UTC, reyraa commented on src/components/shared/transactionSummary/footer.js
> +        }}
Please replace the state hook with a custom hook that validates the second passphrase and stored the `secondPassphrase` as:

```
{
   data: '',
   error: 0,
   feedback: [],
}
```

Where error is `-1` for empty, `0` for valid, and a positive number for the number of errors discovered.
And feedback is an array of strings, each representing an error message.

2022-02-23 07:42 UTC, ManuGowda approved these changes

2022-02-23 07:42 UTC, ManuGowda commented on src/hooks/setSecondPassphrase.js
> +  error: -1,
maybe either `status` or `errorStatus`?

2022-02-23 09:15 UTC, reyraa approved these changes

2022-02-23 09:15 UTC, merged