Hide locked balance arrow button in Dashboard - closes #4197
LiskHQ/lisk-desktop pull request #4199
Opened 2022-03-13 07:52 UTC by vibratious

### What was the problem?

This PR resolves #4197

### How was it solved?
I made icon property in the `WalletDetails` component dynamic, and since I haven't passed this property in Dashboard It wont show up.

### How was it tested?

WIP

2022-03-13 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-desktop?pullRequest=4199) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-desktop?pullRequest=4199) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-desktop?pullRequest=4199) it.</sub>

2022-03-14 07:59 UTC, reyraa requested changes
Hi. 
We appreciate you participating in Lisk Desktop. May I please ask you to fix linting issues?
Thank you

2022-03-14 13:45 UTC, reyraa commented on src/components/screens/dashboard/dashboard.js
> +            {isLoggedIn ? <WalletDetails className={styles.marginFix} isWalletRoute={false} /> : null}
Here you have a linting issue 
```suggestion
            {
              isLoggedIn
                ? <WalletDetails className={styles.marginFix} isWalletRoute={false} />
                : null
            }
```

2022-03-14 14:56 UTC, reyraa approved these changes

2022-03-14 15:08 UTC, gadjacobs approved these changes

2022-03-15 07:06 UTC, merged