Add support for filtering using address - closes #4179
LiskHQ/lisk-desktop pull request #4200
Opened 2022-03-13 13:03 UTC by vibratious

### What was the problem?

This PR resolves #4179

### How was it solved?

I added filtering using address to the votes list

### How was it tested?

visually

2022-03-13 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-desktop?pullRequest=4200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-desktop?pullRequest=4200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-desktop?pullRequest=4200) it.</sub>

2022-03-14 07:55 UTC, reyraa requested changes
Hi,
Thank you for submitting yet another PR. You seem to be having a linting issue. Please fix this issue.
Much appreciated.

2022-03-14 12:50 UTC, reyraa approved these changes

2022-03-14 13:00 UTC, ikem-legend approved these changes

2022-03-14 13:05 UTC, merged