Update npm dependencies - Closes #3818
LiskHQ/lisk-desktop pull request #4219
Opened 2022-03-20 21:02 UTC by eniolam1000752

### What was the problem?

This PR resolves #3818

### How was it solved?

-[-] Added version resolutions to specific node packages with the affected vulnerability.

### How was it tested?

- Running the project's dev server by running `npm run dev`
- Running the project's jest test
- Building the project

2022-03-21 11:17 UTC, ikem-legend submitted a review, later dismissed

2022-03-22 08:43 UTC, isalga submitted a review, later dismissed

2022-03-23 08:13 UTC, ManuGowda requested changes
@eniolam1000752 I tried to checkout this branch and tried to do `npm install` it doesn't seem to work, can you try to follow this step?
- `rm -rf node_modules`
- `npm install`
see if it works.

2022-03-24 12:00 UTC, ManuGowda requested changes

2022-03-24 12:00 UTC, ManuGowda commented on app/package-lock.json
> -  "lockfileVersion": 2,
lockfileVersion 2 is for npm > 7, since we are using node 16 the npm version is 8, so why have you changed it to 1?

2022-03-25 06:07 UTC, ManuGowda approved these changes

2022-03-25 09:45 UTC, ikem-legend approved these changes

2022-03-25 14:56 UTC, merged