Tag e2e scenarios as basic or advanced on jenkins - Closes #4105
LiskHQ/lisk-desktop pull request #4227
Opened 2022-03-23 10:53 UTC by gadjacobs

### What was the problem?

This PR resolves #4105 

### How was it solved?

By adding tags to scenarios and running only basic scenarios on new branches.

### How was it tested?

Jenkins

2022-03-23 14:22 UTC, ManuGowda requested changes
@gadjacobs overall LGTM, why did the package.lock change?

2022-03-24 08:45 UTC, ManuGowda approved these changes

2022-03-24 08:52 UTC, eniolam1000752 requested changes
I think removing package-lock from commit should be all that this PR needs.

2022-03-24 08:57 UTC, ManuGowda approved these changes

2022-03-24 08:58 UTC, eniolam1000752 approved these changes
LGTM

2022-03-24 11:52 UTC, merged