Fix issues discovered with HWs - Closes #4244
LiskHQ/lisk-desktop pull request #4255
Opened 2022-04-07 12:27 UTC by reyraa

### What was the problem?

This PR resolves #4244

### How was it solved?

### How was it tested?

2022-04-08 13:39 UTC, ManuGowda requested changes
Still having the same spinning issue, also I observed other errors this time.

<img width="1439" alt="Screenshot 2022-04-08 at 9 56 12 AM" src="https://user-images.githubusercontent.com/6449871/162447110-a21852e5-4805-45fe-bf1d-9583bc2224fa.png">
<img width="1665" alt="Screenshot 2022-04-08 at 9 54 15 AM" src="https://user-images.githubusercontent.com/6449871/162447103-4eedf7bc-7d86-44df-8320-ee5e1d4b06a4.png">

2022-04-11 15:19 UTC, ManuGowda reviewed
@reyraa the changes LGTM, please address the comment.

2022-04-11 15:19 UTC, ManuGowda commented on src/utils/hwManager.js
> +  console.log('getNewAccountByIndex', deviceId, index);
please remove

2022-04-12 06:46 UTC, ManuGowda approved these changes

2022-04-12 10:12 UTC, Balanced02 approved these changes

2022-04-12 11:30 UTC, merged