4293 implement setup password form
LiskHQ/lisk-desktop pull request #4309
Opened 2022-05-12 09:37 UTC by eniolam1000752

### What was the problem?

This PR resolves #4293

### How was it solved?

- [ ] Create a Global text field component that can be used as a password field
- [ ] Construct form using `react-hook-form`
- [ ] Create validation schemas for the password form 

### How was it tested?

- Visually
- writing jest tests

2022-05-12 10:43 UTC, soroushm commented on package.json
> +    "npm": "8.10.0",
remove npm `install` and `npm` packages

2022-05-17 15:01 UTC, isalga requested changes

2022-05-17 15:01 UTC, isalga commented on src/modules/auth/components/SetPasswordForm/SetPasswordForm.js
> +        <div style={{ padding: '0px 30px' }}>
Put this styles in css please.

2022-05-17 15:01 UTC, isalga commented on src/modules/auth/components/SetPasswordForm/SetPasswordForm.js
> +              <span style={{ display: 'flex', alignItems: 'center' }}>
same

2022-05-18 09:40 UTC, soroushm commented on setup/config/webpack.config.dev.js
> +    // new webpack.IgnorePlugin({ resourceRegExp: /\.\/locale$/ }),
Hi @reyraa,
we had difficulty here .local file was ignored, I believe it had issues at the moment, but now it looks working fine do you know about it?

2022-05-18 09:46 UTC, soroushm submitted a review, later dismissed

2022-05-19 12:41 UTC, ikem-legend approved these changes

2022-05-19 14:34 UTC, soroushm approved these changes

2022-05-19 14:34 UTC, merged