Upload encrypted JSON account page -  Closes #4297
LiskHQ/lisk-desktop pull request #4312
Opened 2022-05-16 11:05 UTC by gadjacobs

### What was the problem?

This PR resolves #4297

### How was it solved?

- [x] Implement upload json file form according to [design](https://www.figma.com/file/GbrsJiZlsh2OzVKqYDD4zI/Account-managing-improvements?node-id=1%3A2563)
- [x] Allow user to select file from disk
- [x] Add Unit test to check validation
- [x] Add unit test to check upload file

### How was it tested?

- Visually
- Unit tests

2022-05-20 09:48 UTC, soroushm commented
Hi @gadjacobs, I update the description and remove the drag and drop part

2022-05-20 15:50 UTC, soroushm approved these changes, later dismissed

2022-05-24 10:45 UTC, soroushm submitted a review, later dismissed

2022-05-24 14:29 UTC, reyraa requested changes
Please delete `testRegisterMultisgn.json` file.  Since now we have removed the drag and drop from the acceptance criteria, we should change the placeholder of the textarea. Make sure the placeholder is hidden when the textarea is full.

2022-05-24 14:29 UTC, reyraa commented on src/modules/auth/components/restoreAccountForm/restoreAccountForm.css
> +
These styles used to be somewhere. Since the removed ones are not in your PR, we have duplicated code. please remvoe them

2022-05-24 14:29 UTC, reyraa commented on src/modules/common/components/uploadJSONInput/uploadJSONInput.css
> +  display: none;
These styles now seem to exist in 3 places. Please keep only one copy

2022-05-24 16:07 UTC, ikem-legend submitted a review, later dismissed

2022-05-25 07:37 UTC, soroushm submitted a review, later dismissed

2022-05-25 07:39 UTC, reyraa approved these changes

2022-05-25 08:22 UTC, soroushm approved these changes

2022-05-25 08:23 UTC, merged