Implement account selector form - Closes #4295
LiskHQ/lisk-desktop pull request #4316
Opened 2022-05-19 20:45 UTC by eniolam1000752

### What was the problem?

This PR resolves #4295

### How was it solved?

- [x] Create Account select form
- [x] create An outline button
- [ ] write unit test

### How was it tested?

- unit test

2022-05-20 14:23 UTC, ManuGowda reviewed
Left few minor comments, some of them need not be addressed for this PR, if its too complex we can do it separately, Nice job 🚀

2022-05-20 14:23 UTC, ManuGowda commented on packages/views/screens/router/routes.js
> +    path: '/manage-account',
can we use path like `/accounts/manage`? and same when we introduce `/accounts/{add, remove}` same applies to other routes where we have domain and subdomains

2022-05-20 14:23 UTC, ManuGowda commented on packages/views/screens/router/routes.js
> +    forbiddenTokens: [tokenMap.BTC.key],
Remove BTC whenever you work on new changes.

2022-05-20 14:23 UTC, ManuGowda commented on src/modules/account/components/AccountSelect/AccountSelect.js
> +      <WalletVisual address={address} size={40} />
This should be more like AccountIcon? I know in the past we might have used it differently but from AccountIcon makes more relatable here?

2022-05-20 14:23 UTC, ManuGowda commented on src/modules/account/components/AccountSelect/AccountSelect.test.js
> +const savedAccounts = [
Move this under test/fixtures? so that it can be reused?

2022-05-20 14:23 UTC, ManuGowda commented on src/modules/account/components/AccountSelect/AccountSelect.test.js
> +describe('Select Account Formshould work', () => {
Account Selector
  Should render list of accounts

2022-05-20 14:23 UTC, ManuGowda commented on src/modules/account/components/AccountSelect/AccountSelect.test.js
> +    expect(screen.getByText('lsk74ar23k2zk3mpsnryxbxf5yf9ystudqmj4oj6e')).toBeTruthy();
use the savedAccounts value to iterate and use savedAccounts.address for value

2022-05-23 07:36 UTC, soroushm approved these changes, later dismissed

2022-05-23 07:36 UTC, soroushm commented on packages/views/screens/router/routes.js
> +    path: '/manage-account',
@eniolam1000752 please remove the route the flow issue will take care of the route

2022-05-23 07:36 UTC, soroushm commented on src/modules/account/components/AccountSelect/AccountSelect.js
> +    <>
@eniolam1000752 please remove unnecessary fragments

2022-05-23 07:49 UTC, ManuGowda requested changes
[@Eniola Olatunji](https://lightcurve.slack.com/team/U02NTBKTAF7) the PR changes looks good, but the CI is failing as the coverage is not met of unit test, please add the missing test scenarios

2022-05-23 13:20 UTC, ManuGowda submitted a review, later dismissed

2022-05-24 07:29 UTC, soroushm approved these changes

2022-05-24 08:15 UTC, soroushm commented
@ManuGowda could you please one again approve the pr

2022-05-24 08:29 UTC, ManuGowda approved these changes

2022-05-24 09:11 UTC, merged