Update sign in/up UI - Closes #4306
LiskHQ/lisk-desktop pull request #4319
Opened 2022-05-23 09:14 UTC by isalga

### What was the problem?

This PR resolves #4306

### How was it solved?

### How was it tested?

2022-05-24 12:16 UTC, eniolam1000752 commented
You've got a failing CI at `unit test` stage due to a lower coverage value

2022-05-24 13:04 UTC, reyraa requested changes, later dismissed
- The copy icon looks different. Can we add the correct one here?
- I can see the sign in button in the register screen, which is fine. But it's missing in the design. Can we get an approval from @ann-vashchenko ?
- Also, the network is visible at the top. But registering an account is not network-specific. I think we should hide it. As it's hidden in the design too. Correct @ann-vashchenko ?
- The color of the subtitle, and the corner raius of the option buttons are different than in the design of the [design](https://www.figma.com/file/GbrsJiZlsh2OzVKqYDD4zI/Account-management-improvements?node-id=1%3A2122)
- There's a delay when the secret is approved. The options turn green, we don't navigate to the next step, but the primary button is still active. should we disable it? should we navigate right away? What is the delay for?

2022-05-30 09:22 UTC, isalga commented
@reyraa, I discussed with @ann-vashchenko and she mentions sign in button has to be removed. For the third point (network) it is out of the scope of this ticket and it needs discussion with @ManuGowda . Right @ann-vashchenko ?

2022-05-30 19:23 UTC, gadjacobs approved these changes, later dismissed

2022-05-31 13:09 UTC, soroushm submitted a review, later dismissed

2022-05-31 13:12 UTC, soroushm commented on src/modules/common/components/bars/topBar/topBar.js
> -        ) : null}
@isalga please revert this sign in button right now application have braking change, this one is not blong to this ticket

2022-05-31 13:44 UTC, soroushm approved these changes

2022-05-31 13:46 UTC, gadjacobs approved these changes

2022-05-31 13:50 UTC, merged