Remove sign in and sign out features - Closes #4317
LiskHQ/lisk-desktop pull request #4324
Opened 2022-05-24 13:39 UTC by isalga

### What was the problem?

This PR resolves #4317

### How was it solved?

- [ ] Remove sign in
- [ ] Remove sign out
- [ ] Remove logic for auto logout
- [ ] Remove unit tests related to sign in and sign out
- [ ] Adopt unit test and e2e test

### How was it tested?

2022-05-31 07:41 UTC, soroushm commented
@isalga please don't merge the pr when is done

2022-05-31 13:52 UTC, soroushm requested changes

2022-05-31 13:52 UTC, soroushm commented on src/modules/auth/components/Signin/login.js
> +              {/** canHWSignIn ? (
please revert all logic about the hardware wallet

2022-05-31 13:52 UTC, soroushm commented on src/modules/auth/store/action.js
> +// import { extractAddress as extractBitcoinAddress } from '@wallet/utils/api';
bitcoin and token map is out of the scope pleaser revert other wise it will get conflict with the other pr

2022-05-31 13:52 UTC, soroushm commented on src/modules/common/components/bars/topBar/signOut.js
> -import { useDispatch } from 'react-redux';
remove the hole component and usages

2022-05-31 13:52 UTC, soroushm commented on src/modules/legacy/store/middleware.js
> +/** const checkAccountMigrationState = (action) => {
this logic is non related to the login process please revert it

2022-05-31 13:52 UTC, soroushm commented on src/modules/common/components/bars/topBar/index.js
>    resetTimer: () => timerReset(),
timerReset is the part of auto logout so you need to remove it

2022-05-31 13:57 UTC, ikem-legend submitted a review, later dismissed

2022-06-01 13:24 UTC, ikem-legend commented on setup/react/app/index.test.js
>          token: {
@isalga `token` should also be removed as it's no longer part of the settings

2022-06-01 13:29 UTC, ikem-legend commented on src/modules/settings/store/reducer.test.js
>          list: {
@isalga `token` should also be removed from the settings object here too

2022-06-01 13:30 UTC, ikem-legend commented on src/modules/legacy/store/middleware.js
> +  if (action.type === actionTypes.accountLoggedIn || action.type === actionTypes.accountUpdated) {
@isalga If `accountLoggedIn` has been removed, then this condition should also be changed

2022-06-01 14:24 UTC, reyraa submitted a review, later dismissed
Good job @isalga!

2022-06-01 14:25 UTC, ikem-legend submitted a review, later dismissed

2022-07-04 07:29 UTC, ManuGowda commented
This pull request can not be merged unless the change API objective is completed to support the way login to account to be able to create transaction or access endpoints. All of the SDK v5 features are closely integrated, so we intend to keep this PR until v6 API integration is completed.

2022-08-17 17:33 UTC, eniolam1000752 requested changes
I think most of the e2e tests whose pages are private routes(i.e depended on login) might fail.

2022-08-17 17:33 UTC, eniolam1000752 commented on src/modules/settings/store/reducer.test.js
> +      data: { testSetting: false },
the naming convention here seems confusing possibly the term `useTestSetting` would be okay I think

2022-08-22 19:19 UTC, soroushm commented on src/modules/settings/store/reducer.test.js
> +      data: { testSetting: false },
@eniolam1000752 we dont need this settings anymore could you please remove it

2022-09-06 08:32 UTC, soroushm approved these changes

2022-09-06 08:33 UTC, reyraa approved these changes

2022-09-06 08:42 UTC, eniolam1000752 approved these changes
LGTM

2022-09-06 08:44 UTC, merged