Implement add account with recovery file flow - Closes #4303
LiskHQ/lisk-desktop pull request #4332
Opened 2022-05-31 11:51 UTC by isalga

### What was the problem?

This PR resolves #4303

### How was it solved?

WIP

### How was it tested?

WIP

2022-06-07 13:45 UTC, soroushm requested changes

2022-06-07 13:45 UTC, soroushm commented on src/modules/account/components/AddAccountByFile/AddAccountByFile.js
> +      <EnterPasswordForm onEnterPasswordSuccess={onEnterPasswordSuccess} />
the last step is "Perfect! You're all set" the component name i this is passwordSuccessed

2022-06-07 14:12 UTC, ikem-legend reviewed
`EnterPasswordForm` does not submit on pressing the Enter key

2022-06-07 15:59 UTC, soroushm commented
> `EnterPasswordForm` does not submit on pressing the Enter key

Good catch, it wasnt in the requirment, let me check with ana and manu after that we can add it

2022-06-08 09:52 UTC, ikem-legend approved these changes, later dismissed

2022-06-10 15:09 UTC, soroushm approved these changes

2022-06-10 15:15 UTC, ikem-legend approved these changes

2022-06-10 15:17 UTC, merged