Implement switch account modal - Closes #4300
LiskHQ/lisk-desktop pull request #4339
Opened 2022-06-08 22:17 UTC by isalga

### What was the problem?

This PR resolves #4300

### How was it solved?

WIP

### How was it tested?

WIP

2022-06-14 08:55 UTC, soroushm requested changes

2022-06-14 08:55 UTC, soroushm commented on src/modules/account/components/SwitchAccount/SwitchAccount.js
> +import React from 'react';
I believe this component is duplicated 
you can reuse the ManageAccounts

2022-06-15 10:29 UTC, soroushm commented
you need to reuse account manage component to a page  and make it center

2022-06-15 11:48 UTC, isalga commented
How is it in design? it is a dialog. Do it you. You decide everything all the time and change team decitions constantly.

2022-06-20 08:36 UTC, ikem-legend commented on setup/jest.config.js
> +  collectCoverage: false,
@isalga @eniolam1000752 Please revert coverage

2022-06-20 14:06 UTC, ikem-legend submitted a review, later dismissed

2022-06-20 14:07 UTC, soroushm requested changes

2022-06-20 14:07 UTC, soroushm commented on src/modules/account/components/SwitchAccount/SwitchAccount.js
> +    <ManageAccounts title={t('Switch account')} />
```suggestion
    <ManageAccounts title={t('Switch account')} isRemoveAvailable={false} />
```

2022-06-20 14:37 UTC, isalga commented on src/modules/account/components/SwitchAccount/SwitchAccount.js
> +    <ManageAccounts title={t('Switch account')} />
Changed, but I think both solutions are equally valid.

2022-06-20 14:54 UTC, soroushm approved these changes

2022-06-20 14:55 UTC, soroushm commented on src/modules/account/components/SwitchAccount/SwitchAccount.js
> +    <ManageAccounts title={t('Switch account')} />
I didn't notice changes related about this, could we have short call and explain to me?

2022-06-20 15:40 UTC, ikem-legend approved these changes

2022-06-20 15:46 UTC, merged