Update initial routes to new account management - Closes #4350
LiskHQ/lisk-desktop pull request #4351
Opened 2022-06-23 07:26 UTC by gadjacobs

### What was the problem?

This PR resolves #4350 

### How was it solved?

WIP

### How was it tested?

WIP

2022-06-23 08:09 UTC, soroushm requested changes

2022-06-23 08:09 UTC, soroushm commented on src/modules/common/components/customRoute/index.js
> +  if (!isAuthenticated && path === routes.dashboard.path) {
!isAuthenticated && path === '/'

2022-06-23 08:09 UTC, soroushm commented on src/modules/common/components/customRoute/index.js
>    const isAuthenticated = !!wallet.summary;
```suggestion
const [account] = useCurrentAccount()
  const isAuthenticated = !!account
```

2022-06-23 09:45 UTC, ManuGowda requested changes
@gadjacobs left few minor comments.

2022-06-23 09:45 UTC, ManuGowda commented on src/modules/common/components/customRoute/index.js
> +  console.log('current acc--', account);
Please remove

2022-06-23 09:45 UTC, ManuGowda commented on src/modules/common/components/customRoute/index.js
> +  const hasAccounts = accounts.length > 0;
if the logic is not reused, its better to use them directly to avoid unnecessary allocation

2022-06-23 09:45 UTC, ManuGowda commented on packages/views/screens/router/routes.js
> +    path: '/',
@soroushm the default route is not finalised yet, for now i understand we do not have sign in anymore and this is ok. But we might want to change this at later point in time based on new design changes to dashboard

2022-06-30 13:18 UTC, ikem-legend approved these changes

2022-06-30 13:20 UTC, ManuGowda commented on src/modules/common/components/customRoute/index.js
> +  if (!isAuthenticated && path === routes.manageAccounts.path && !(accounts.length > 0)) {
this is redundant? `!(accounts.length > 0)` it is same as `!isAuthenticated`

2022-06-30 13:22 UTC, soroushm commented on src/modules/common/components/customRoute/index.js
> +  if (!isAuthenticated && path === routes.manageAccounts.path && !(accounts.length > 0)) {
@ManuGowda accounts is the list of account from the account manager

2022-06-30 14:18 UTC, ManuGowda approved these changes

2022-06-30 14:19 UTC, ManuGowda approved these changes

2022-07-01 08:34 UTC, ikem-legend approved these changes

2022-07-01 09:38 UTC, soroushm approved these changes

2022-07-01 09:38 UTC, merged