Implemented initial hook with related Redux setup
LiskHQ/lisk-desktop pull request #4388
Opened 2022-07-06 01:43 UTC by ikem-legend

### What was the problem?

This PR resolves #4371

### How was it solved?

- [ ] Fetch list of applications
- [ ] Enable ‘isPin’ flag for default applications from `useApplicationsPin` hooks then sort the list by pinned priority
- [ ] Enable memoization for applications
- [ ] Update status by fetching status from the server
- [ ] Implement `setApplication` method to enable users to add an application to the store
- [ ] Implement `getApplicationByChainId` to enable users to fetch a specific application by chainId
- [ ] Implement `deleteApplicationByChainId` to enable users to remove specific application by chainId from local storage

### How was it tested?

Via unit tests

2022-07-11 16:09 UTC, soroushm submitted a review, later dismissed

2022-07-11 16:09 UTC, soroushm commented on src/modules/blockchainApplication/manage/store/action.js
> +});
a bit wired to me passing data here shall we pass chainId
```suggestion
export const deleteApplication = (chainId) => ({
  type: actionTypes.deleteApplicationByChainId,
  chainId,
});
```

2022-07-11 16:09 UTC, soroushm commented on src/modules/blockchainApplication/manage/store/reducer.js
> +    }
improve naming please data is a bit wired for me
```suggestion
export const applications = (state = initialState.applications, { type, application, chainId }) => {
  switch (type) {
    case actionTypes.addApplicationByChainId:
      // In cases where a new node for an existing application is being added,
      // the new node url should be appended to the nodeURL array of the application
      if (application.chainID in state) {
        state[application.chainID].nodeURL.push(data.nodeURL);
      } else {
        state[application.chainID] = data;
      }
      return state;

    case actionTypes.deleteApplicationByChainId: {
      delete state[chainId];
      return { ...state };
    }
```

2022-07-11 17:18 UTC, eniolam1000752 requested changes

2022-07-11 17:18 UTC, eniolam1000752 commented on tests/fixtures/blockchainApplicationsManage.js
> +    serviceURL: ['https://service.colecti.com'],
this should be `serviceURL`

2022-07-12 07:31 UTC, soroushm approved these changes

2022-07-12 07:44 UTC, eniolam1000752 approved these changes
LGTM

2022-07-12 08:57 UTC, merged