4398 adjust switch application flow
LiskHQ/lisk-desktop pull request #4408
Opened 2022-07-26 23:40 UTC by ikem-legend

### What was the problem?

This PR resolves #4398

### How was it solved?

- [ ] Enable users to select node url if there is more than one

### How was it tested?

- [ ] Unit tests
- [ ] Visually

2022-07-28 07:30 UTC, ManuGowda commented
@ikem-legend looks like the PR has 41 files? maybe rebasing required?

2022-07-28 07:34 UTC, ikem-legend commented
> @ikem-legend looks like the PR has 41 files? maybe rebasing required?

@ManuGowda While working on the ticket, I moved some files from the previous PR and updated the imports. That's why there's such a number of files

2022-07-29 09:17 UTC, eniolam1000752 requested changes
UI Review comments

- height on figma is `48px` but here is `38px` (I think you can adjust this from its padding since on figma it says 16px but 8px was used).
<img width="759" alt="image" src="https://user-images.githubusercontent.com/32064769/181725831-b2eee7e1-75ac-48ac-b151-917b4b87761f.png">

- figma says the back button is 20px by 20px but here is 24px by 28px and its kind of not aligned with the close button.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/32064769/181726509-41e85a2a-0122-4829-8703-2edb41fdaa2d.png">

- dark mode styles were not factored in 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/32064769/181727204-43ba91ae-fcfb-4596-b9df-ee80ed33a478.png">


-

2022-07-29 09:19 UTC, eniolam1000752 commented
@ikem-legend  I think you should extend the e2e tests scenario on the switch blockchain application flow to consider a case where a blockchain has more than one nodeUrl

2022-07-29 16:43 UTC, ikem-legend commented
> UI Review comments
> 
> * height on figma is `48px` but here is `38px` (I think you can adjust this from its padding since on figma it says 16px but 8px was used).
> 
> <img alt="image" width="759" src="https://user-images.githubusercontent.com/32064769/181725831-b2eee7e1-75ac-48ac-b151-917b4b87761f.png">
> 
> * figma says the back button is 20px by 20px but here is 24px by 28px and its kind of not aligned with the close button.
> 
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/32064769/181726509-41e85a2a-0122-4829-8703-2edb41fdaa2d.png">
> 
> * dark mode styles were not factored in
> 
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/32064769/181727204-43ba91ae-fcfb-4596-b9df-ee80ed33a478.png">

@eniolam1000752 Resolved

2022-07-29 16:43 UTC, ikem-legend commented
> @ikem-legend I think you should extend the e2e tests scenario on the switch blockchain application flow to consider a case where a blockchain has more than one nodeUrl

@eniolam1000752 Done

2022-07-29 16:59 UTC, eniolam1000752 requested changes
I just picked this up, there is no horizontal padding here

<img width="682" alt="image" src="https://user-images.githubusercontent.com/32064769/181808397-6e955219-5751-43a6-a7ff-ec0038902669.png">

2022-07-29 19:14 UTC, ikem-legend commented
> I just picked this up, there is no horizontal padding here
> 
> <img alt="image" width="682" src="https://user-images.githubusercontent.com/32064769/181808397-6e955219-5751-43a6-a7ff-ec0038902669.png">

@eniolam1000752 Fixed

2022-07-31 21:59 UTC, eniolam1000752 approved these changes, later dismissed

2022-08-01 17:19 UTC, eniolam1000752 reviewed
There were no updated e2e tests due to these last changes. weird 🤔

2022-08-01 21:00 UTC, eniolam1000752 submitted a review, later dismissed

2022-08-02 09:23 UTC, ManuGowda commented on src/modules/blockchainApplication/manage/components/SelectNode/SelectNode.js
> +            <img src={chainLogo || liskLogo} />
`liskLogo || chainLogo`?

2022-08-02 09:23 UTC, ManuGowda commented on src/modules/blockchainApplication/manage/components/SelectNode/SelectNode.test.js
> +  it('displays properly', () => {
```suggestion
  it('Should render select node component', () => {
```

2022-08-02 09:23 UTC, ManuGowda commented on src/modules/blockchainApplication/manage/store/reducer.test.js
>          chainID: 'aq02qkbb35u4jdq2szo6ytre',
this will be integer, just for consistency can you update all the mock data to integer? sample value `0001`

2022-08-02 09:23 UTC, ManuGowda commented on tests/fixtures/blockchainApplicationsManage.js
>      chainID: 'aq02qkbb35u4jdq8szo3pnsq',
same here, please update the fixture

2022-08-02 09:29 UTC, ManuGowda commented on src/modules/blockchainApplication/manage/components/SelectNode/SelectNode.js
> +            <img src={chainLogo || liskLogo} />
invalid comment

2022-08-02 09:33 UTC, ManuGowda approved these changes

2022-08-02 09:33 UTC, ManuGowda approved these changes

2022-08-02 10:08 UTC, eniolam1000752 approved these changes

2022-08-02 10:37 UTC, merged