Implement new user menu - Closes #4468
LiskHQ/lisk-desktop pull request #4478
Opened 2022-09-13 17:36 UTC by ikem-legend

### What was the problem?

This PR resolves #4468

### How was it solved?

Updating the UI to the new [UI design](https://www.figma.com/file/9JbvSmtLNJIttXp68uhmQR/Change-API-to-support-Lisk-SDK-v6-API?node-id=836%3A87932)

### How was it tested?

Visually

2022-09-14 11:54 UTC, Balanced02 submitted a review, later dismissed
LGTM!

2022-09-14 12:17 UTC, Balanced02 submitted a review, later dismissed

2022-09-14 14:44 UTC, soroushm requested changes

2022-09-14 14:44 UTC, soroushm commented on src/modules/account/components/AccountManagementDropdown/AccountManagementDropdown.css
> +  background-color: var(--color-background-dropdown);
background color dosn't match with design
color : #030815

2022-09-14 14:44 UTC, soroushm commented on src/modules/account/components/AccountManagementDropdown/AccountManagementDropdown.js
> +        {ACCOUNT_MENU.map(({ path, icon, label, component }) => (
remove account should be red

2022-09-14 15:06 UTC, soroushm requested changes

2022-09-14 15:06 UTC, soroushm commented on src/modules/account/const/accountMenu.js
> +    path: modals.multiSignature.path,
```suggestion
    path: `/delegates?modal=registerDelegate`,
```

2022-09-14 16:26 UTC, ikem-legend commented on src/modules/account/const/accountMenu.js
> +    path: modals.multiSignature.path,
@soroushm Fixed

2022-09-14 16:27 UTC, ikem-legend commented on src/modules/account/components/AccountManagementDropdown/AccountManagementDropdown.js
> +        {ACCOUNT_MENU.map(({ path, icon, label, component }) => (
@soroushm Done

2022-09-14 16:27 UTC, ikem-legend commented on src/modules/account/components/AccountManagementDropdown/AccountManagementDropdown.css
> +  background-color: var(--color-background-dropdown);
@soroushm Fixed

2022-09-14 17:17 UTC, Balanced02 submitted a review, later dismissed

2022-09-15 12:42 UTC, soroushm commented on src/theme/dialog/holder.js
> +  const isAuthenticated = Object.keys(account).length > 0 || !!wallet.summary;
selectActiveTokenAccount is deprecated now
```suggestion
  const [account] = useCurrentAccount();
  const isAuthenticated = Object.keys(account).length > 0;
```

2022-09-15 12:47 UTC, soroushm commented
@ikem-legend background only will change  while menu is open
https://www.figma.com/file/9JbvSmtLNJIttXp68uhmQR/Change-API-to-support-Lisk-SDK-v6-API?node-id=492%3A47457

2022-09-15 17:19 UTC, soroushm approved these changes

2022-09-15 17:36 UTC, Balanced02 approved these changes

2022-09-15 17:37 UTC, merged