Integrate application management endpoint - Closes #4489
LiskHQ/lisk-desktop pull request #4495
Opened 2022-10-05 22:01 UTC by Balanced02

### What was the problem?

This PR resolves #4489 

### How was it solved?

- [x] Integrate Applications Management with api
- [x] Integrate Applications Statistics with api
- [x] Integrate Application Details with api
- [x] Ensure adding and switching applications work

### How was it tested?

- [x] Browser
- [x] Updated/Added Unit tests

2022-10-12 10:15 UTC, soroushm requested changes

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/components/BlockchainApplicationDetails/BlockchainApplicationDetails.js
> +  const application = useBlockchainApplicationMeta({ config: { params: { chainID: '00000001' } } })
Kindly, please fix the chain id from location

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/components/BlockchainApplicationDetails/BlockchainApplicationDetails.js
>              <a
https://docs.google.com/document/d/1fId3uEv1xLfXxBI3sipIGPWl4YiN9caheuQIRZ68VVk/edit#
```suggestion
          blockchain.explorers.map(({url}) =>  <a
              className={`${styles.appLink}`}
              target="_blank"
              href={url}
            >
              <Icon name="chainLinkIcon" className={styles.hwWalletIcon} />
              {url}
            </a>)
```

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.js
> + * @param {Object} options - Custom options for the query.
please update docs with params

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.test.js
> +    const wrapper = ({ children }) => (
please use queryWrapper 
```
import { queryWrapper as wrapper } from 'src/utils/test/queryWrapper';
```

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.test.js
> +  <Provider store={reduxStore}>{children}</Provider>
useQuery nothing to do with redux

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.js
> +export default function useApplicationsQuery(chainID, { config: customConfig = {}, options = {} } = {}) {
kindly please change the `useApplicationsQuery` to `useApplications` 
to match with the rest of hooks

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js
> +export default function useBlockchainApplicationExplore() {
here its need to call the meta endpoint to add meta data inside the application

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js
> +  return applications
the pagination is missing

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationStatistics.js
> +export default function useBlockchainApplicationStatistics() {
we are not using export default any more

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/manage/components/AddApplicationList/AddApplicationList.js
> +    fetchNextPage(params)
fetchNextPage dosn't need params its already handled inside the infiniteQuery

2022-10-12 10:15 UTC, soroushm commented on src/modules/blockchainApplication/manage/components/AddApplicationList/AddApplicationList.test.js
> +useApplicationsQuery.mockReturnValue({
please avoid mocking queries lets return data from msw

2022-10-12 10:15 UTC, soroushm commented on src/utils/api/constants.js
> +export const API_BASE_URL = 'http://165.22.29.229:9901';
we have this data in `src/const/config` pleaase avoid dublication

2022-10-20 19:28 UTC, Balanced02 commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.test.js
> +  <Provider store={reduxStore}>{children}</Provider>
...the `useInfiniteQuery` needs to get `currentApplication` from redux; other option is to mock the implementation of `useCustomInfiniteQuery`

2022-10-20 19:29 UTC, Balanced02 commented on src/modules/blockchainApplication/explore/hooks/queries/useApplicationsQuery.test.js
> +    const wrapper = ({ children }) => (
...same reason above; needs redux

2022-10-25 07:23 UTC, Balanced02 commented
Did a re-work in a different branch

2022-10-25 07:23 UTC, closed without merging