Update token transfer form
LiskHQ/lisk-desktop pull request #4547
Opened 2022-10-31 20:07 UTC by ikem-legend

### What was the problem?

This PR resolves #4528

### How was it solved?

- Updating the UI based on the new design

### How was it tested?

- [x] Manually

2022-11-01 10:14 UTC, eniolam1000752 requested changes

2022-11-01 10:14 UTC, eniolam1000752 commented on src/modules/token/fungible/components/SendForm/SendForm.js
> +      token: recipientChain,
this seems weird @ikem-legend

2022-11-01 10:14 UTC, eniolam1000752 commented on src/modules/token/fungible/components/SendForm/SendForm.js
>                    {token?.symbol}
balance should only show when a token has been selected

2022-11-01 10:15 UTC, eniolam1000752 commented
unit test needs to be fixed too

2022-11-01 11:42 UTC, ikem-legend commented on src/modules/token/fungible/components/SendForm/SendForm.js
> +      token: recipientChain,
@eniolam1000752 One of the utils for converting desktop transactions to element transactions breaks if token isn't part of the raw transaction params, hence this change

2022-11-01 11:43 UTC, ikem-legend commented on src/modules/token/fungible/components/SendForm/SendForm.js
>                    {token?.symbol}
@eniolam1000752 Balance is currently blank until a token is selected

2022-11-02 12:18 UTC, eniolam1000752 commented on src/modules/token/fungible/components/SendForm/SendForm.js
> +      token: recipientChain,
hmmm so what I mean is that the key `token` and the value `receipientChain` don't refer to the same thing

2022-11-02 15:17 UTC, eniolam1000752 submitted a review, later dismissed

2022-11-02 16:36 UTC, sridharmeganathan approved these changes, later dismissed

2022-11-03 11:16 UTC, eniolam1000752 approved these changes

2022-11-03 11:16 UTC, merged