Create a hook to provide the latest block information - Closes #4507
LiskHQ/lisk-desktop pull request #4607
Opened 2022-11-24 08:11 UTC by reyraa

### What was the problem?

This PR resolves #4507

### How was it solved?

- [x] Create useLatestBlock hook
- [x] Remove blocks redux store, corresponding actions, reducer, and middleware
- [x] Update components to use the new hook instead of Redux store
- [x] Refactor actions that use the obsolete latestBlocks array.

### How was it tested?
- [ ] Ensure the app works as it did before
- [ ] Update unit tests

2022-11-28 10:55 UTC, soroushm requested changes

2022-11-28 10:55 UTC, soroushm commented on src/modules/block/hooks/queries/useLatestBlock.js
> +  };
lets avoid make duplication
```suggestion
  const config = {
    params: {
      limit: 1,
    },
  };
  const response = useBlocks({config})

  return {
    ...response,
    data: response.data?.data[0] ?? { height: 0, timestamp: 0 },
  };
```

2022-11-28 16:23 UTC, ikem-legend commented on src/modules/dpos/validator/components/EditVote/index.test.js
> +    useLatestBlock.mockReturnValue({ data: mockBlocks });
```suggestion
    useLatestBlock.mockReturnValue({
      data: mockBlocks.data[0],
    });
```

2022-11-28 16:23 UTC, ikem-legend commented on src/modules/transaction/components/RecentTransactions/RecentTransactions.test.js
> +
@eniolam1000752 Please remove unnecessary empty line

2022-11-28 16:23 UTC, ikem-legend commented on src/modules/wallet/components/overview/overview.test.js
>  jest.mock('@block/hooks/queries/useBlocks');
@eniolam1000752 `useBlocks` is no longer in use and so the mock should be removed

2022-11-28 16:23 UTC, ikem-legend commented on src/modules/wallet/components/overview/overview.test.js
>      useBlocks.mockReturnValue({ data: mockBlocks });
@eniolam1000752 As mentioned earlier, this should be removed too

2022-11-29 15:55 UTC, ikem-legend approved these changes

2022-11-30 09:13 UTC, soroushm approved these changes

2022-11-30 09:13 UTC, merged