Updated fee logic
LiskHQ/lisk-desktop pull request #4611
Opened 2022-11-25 19:37 UTC by ikem-legend

### What was the problem?

This PR resolves #4529

### How was it solved?

By updating the fee calculation logic

### How was it tested?

- Manually

2022-11-28 23:07 UTC, eniolam1000752 requested changes

2022-11-28 23:07 UTC, eniolam1000752 commented on src/modules/transaction/api/index.js
> +        signatures: new Array(numberOfSignatures).fill(0).map(() => Buffer.alloc(64)),
Also, I think this should not be done this way only empty signatures should be replaced with an empty buffer, this is because when members are signing, there could be empty signatures(meaning a member is yet to sign) and there could be actual signatures(meaning a member has signed). so in this case I think it can be done like this @ikem-legend 

```suggestion
        ...(numberOfSignatures && !transactionObject.params. signatures.length && { signatures: Array(numberOfSignatures).fill(Buffer.alloc(64)) }) ,
```

2022-11-29 11:26 UTC, ikem-legend commented on src/modules/transaction/api/index.js
> +        signatures: new Array(numberOfSignatures).fill(0).map(() => Buffer.alloc(64)),
@eniolam1000752 Fixed

2022-11-29 11:27 UTC, eniolam1000752 approved these changes, later dismissed

2022-11-29 14:31 UTC, eniolam1000752 approved these changes

2022-11-30 11:27 UTC, soroushm approved these changes
LGTM

2022-11-30 11:27 UTC, merged