Update applications and other domain texts
LiskHQ/lisk-desktop pull request #4683
Opened 2022-12-27 15:14 UTC by ManuGowda

### What was the problem?

This PR resolves #4601 

### How was it solved?

:memo: Update grammer and sentences

### How was it tested?

- Updated tests
- Run and review the application

2022-12-28 10:02 UTC, soroushm requested changes

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/BackupRecoveryPhraseFlow/BackupRecoveryPhraseFlow.js
> +          <SavePassphrase passphrase={passphrase} title='Back up your secret recovery phrase' />
please translate it here
```suggestion
          <SavePassphrase passphrase={passphrase} title={t('Back up your secret recovery phrase')} />
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/auth/components/EnterPasswordForm/EnterPasswordForm.js
> +          {t(title || 'Please enter your account password to backup the secret recovery phrase.')}
i18n scan cant scan it in this way
```suggestion
          {title || t('Please enter your account password to backup the secret recovery phrase.')}
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/AddAccountForm/AddAccountForm.js
> +              <label>{t('Secret recovery phrase (12 -24 paraphase supported)')}</label>
typo
```suggestion
              <label>{t('Secret recovery phrase (12-24 paraphrase supported)')}</label>
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/EditAccount/EditAccount.js
> +        contentText={t('Successfully edited the account name, now you can download the encrypted secret recovery phrase to this effect.')}
its a bit too long could we make it shorter?
```suggestion
        contentText={t('Successfully edited, now you can download the encrypted secret recovery phrase to this effect.')}
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/EditAccount/EditAccount.js
> +        contentText={t('Successfully edited the account name, now you can download the encrypted secret recovery phrase to this effect.')}
its a bit too long could we make it shorter?
```suggestion
        contentText={t('Successfully edited, now you can download the encrypted secret recovery phrase to this effect.')}
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/AddAccountForm/AddAccountForm.js
> +              <label>{t('Secret recovery phrase (12 -24 paraphase supported)')}</label>
shouldnt be called phrase like the other places?

2022-12-28 10:02 UTC, soroushm commented on src/modules/account/components/AddAccountOptions/AddAccountOptions.js
> +                text="Restore from backup"
```suggestion
                text={t("Restore from backup")}
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/auth/components/SavePassphrase/SavePassphrase.js
> +      <h1>{t(title ?? 'Save your secret recovery phrase')}</h1>
```suggestion
      <h1>{title || t( 'Save your secret recovery phrase')}</h1>
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/auth/components/SetPasswordSuccess/SetPasswordSuccess.js
> +    error: 'no encrypted back up found',
```suggestion
    error: 'no encrypted backup found',
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/common/components/DownloadJSON/DownloadJSON.js
> +    error: 'no encrypted back up found',
```suggestion
    error: 'no encrypted backup found',
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/message/components/signMessageView/index.js
> +        )}
please avoid duplication
```suggestion
        {(multiStepPosition === 0 || multiStepPosition === 2) && (
          <BoxHeader>
            <h1>{t('Sign message')}</h1>
          </BoxHeader>
        )}
       
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/message/components/signMessageView/index.js
> +        )}
better option
```suggestion
const hasHeader = multiStepPosition === 0 || multiStepPosition === 2
        {hasHeader && (
          <BoxHeader>
            <h1>{t('Sign message')}</h1>
          </BoxHeader>
        )}
       
```

2022-12-28 10:02 UTC, soroushm commented on src/modules/message/components/signMessageView/index.js
> +    console.log('....', current);
remove console.log
```suggestion

```

2022-12-28 10:02 UTC, soroushm commented on src/utils/paperWallet.js
> +    this.doc.text(t('Save it on an encrypted hard drive: USB key or a back up drive'), 76, 238, textOptions);
same here

2022-12-28 12:53 UTC, ManuGowda commented on src/modules/message/components/signMessageView/index.js
> +        )}
The header needs to change based on the state, once the message is signed it shouldn't be called `Sign message`? so it was updated to `Signed message`.

2022-12-28 14:55 UTC, soroushm commented on src/modules/message/components/signMessageView/index.js
> +        )}
we can have the condition only for text
```suggestion
        {multiStepPosition !== 1 && (
          <BoxHeader>
            <h1>{multiStepPosition === 2 ? t('Signed message')  : t('Sign message')}</h1>
          </BoxHeader>
        )}
       
```

2022-12-29 08:57 UTC, soroushm approved these changes

2022-12-29 09:17 UTC, merged