Missing multisignature account details view
LiskHQ/lisk-desktop pull request #4700
Opened 2023-01-04 16:02 UTC by reyraa

### What was the problem?

This PR resolves #4621

### How was it solved?

- Added missing icon in the explorer page
- Added missing UI elements in the dialog view

### How was it tested?

- Visually compared to the designs
- Updated unit tests

2023-01-05 17:54 UTC, ManuGowda requested changes
![Screenshot 2023-01-05 at 6 50 02 PM](https://user-images.githubusercontent.com/6449871/210847310-48b97653-1ae9-46be-aca2-20f4f2a85ade.png)
![Screenshot 2023-01-05 at 6 50 57 PM](https://user-images.githubusercontent.com/6449871/210847312-c692ce87-4a6b-4e17-961e-0be2e8d8136e.png)

2023-01-06 10:22 UTC, oskarleonard commented on src/modules/wallet/components/multisigAccountDetails/index.js
> +import defaultBackgroundImage from '../../../../../setup/react/assets/images/default-chain-background.png';
Maybe use our aliases? 
`@setup/...`

2023-01-06 10:23 UTC, oskarleonard commented on src/modules/wallet/components/multisigAccountDetails/index.js
> +// import BoxHeader from 'src/theme/box/header';
comment

2023-01-06 10:27 UTC, oskarleonard commented on src/modules/wallet/components/walletVisualWithAddress/index.js
> +  <span className={`${styles.address} accountAddress`}>
We cannot have divs inside spans, both CopyToClipboard and DialogLink are divs

2023-01-09 13:11 UTC, oskarleonard approved these changes, later dismissed

2023-01-09 14:52 UTC, oskarleonard approved these changes

2023-01-09 22:27 UTC, ManuGowda approved these changes

2023-01-10 08:19 UTC, merged