Refactor validator registration and staking
LiskHQ/lisk-desktop pull request #4705
Opened 2023-01-09 18:59 UTC by ManuGowda

### What was the problem?

This PR resolves #4702

### How was it solved?

- Rename remaining changes from delegate to validator Rename votes related terminology to stakes
- Created new hooks to resolve staking issues
- At this checkpoint register validator, staking, unstaking transactions are working

### How was it tested?

TODO

2023-01-10 17:08 UTC, oskarleonard approved these changes, later dismissed

2023-01-10 17:40 UTC, oskarleonard approved these changes, later dismissed

2023-01-10 18:22 UTC, soroushm requested changes

2023-01-10 18:22 UTC, soroushm commented on src/modules/legacy/store/action.test.js
> +      moduleCommand: 'legacy:reclaimLSKLSK',
Its looks off to me

2023-01-11 10:34 UTC, oskarleonard approved these changes

2023-01-11 10:36 UTC, merged