4465 replace hardcoded lisk logo
LiskHQ/lisk-desktop pull request #4835
Opened 2023-02-28 11:57 UTC by ikem-legend

### What was the problem?

This PR resolves #4465

### How was it solved?

- Using the getLogo util function to get the right application logo

### How was it tested?

- Visually

2023-03-01 10:05 UTC, oskarleonard approved these changes, later dismissed

2023-03-01 12:42 UTC, eniolam1000752 requested changes
I guess this ticke was suppose to replace all hardcoded token logo. But it seems its still not replaced in some areas eg. the on the wallets page
![image](https://user-images.githubusercontent.com/32064769/222142413-c7ca18c5-043f-433f-9924-df57a6fec1f6.png)

2023-03-01 12:42 UTC, eniolam1000752 commented on src/modules/blockchainApplication/manage/components/RemoveApplicationDetails/RemoveApplicationDetails.js
>  // import useApplicationManagement from '../../hooks/useApplicationManagement';
I guess this comment should be removed

2023-03-01 18:31 UTC, ikem-legend commented on src/modules/blockchainApplication/manage/components/RemoveApplicationDetails/RemoveApplicationDetails.js
>  // import useApplicationManagement from '../../hooks/useApplicationManagement';
@eniolam1000752 Resolved

2023-03-02 12:56 UTC, oskarleonard approved these changes

2023-03-02 14:16 UTC, eniolam1000752 approved these changes

2023-03-02 14:54 UTC, merged