Address send token objective feedback
LiskHQ/lisk-desktop pull request #4879
Opened 2023-03-27 13:24 UTC by eniolam1000752

### What was the problem?

This PR resolves #4450

### How was it solved?

- [x] Introduce feedback to the `MessageField` component
- [x] Modify AmountField to validate against maximum decimal value
- [x] fix failing unit tests

### How was it tested?

- Jest
- Visually

2023-03-27 16:59 UTC, ManuGowda requested changes

2023-03-27 16:59 UTC, ManuGowda commented on src/const/regex.js
> +      maxFloating: (token) => {
```suggestion
      maxDecimals: (token) => {
```

2023-03-27 16:59 UTC, ManuGowda commented on src/locales/en/common.json
> +  "Maximum allowed decimal point is 8.": "Maximum allowed decimal point is 8.",
Shouldn't this be template? based on your implementation 

```
message: i18n.t(`Maximum allowed decimal point is ${getTokenDecimals(token)}.`),
```

2023-03-27 16:59 UTC, ManuGowda commented on src/modules/token/fungible/components/MessageField/MessageField.js
> +  maxCharSize: 'Message size has exceeded the maxium allowed size',
```suggestion
  maxCharSize: 'Message size has exceeded the maximum allowed size',
```

2023-03-27 16:59 UTC, ManuGowda commented on src/modules/token/fungible/components/MessageField/MessageField.js
> +    setFeedBackType(maxMessageLength - byteCount < 0 ? 'maxCharSize' : null);
```suggestion
    setFeedbackType(maxMessageLength - byteCount < 0 ? 'maxCharSize' : null);
```

2023-03-27 16:59 UTC, ManuGowda commented on src/modules/token/fungible/hooks/useAmountField.js
> +    const isMaxAccuracyInValid = maxFloating(token).test(value);
```suggestion
    const isAmountValid = maxFloating(token).test(value);
```

2023-03-27 16:59 UTC, ManuGowda commented on src/modules/token/fungible/hooks/useAmountField.js
>    const onAmountInputChange = ({ value }, maxAmount) => {
can we use `amount`? that way its more readable, i.e `({ value: amount }, maxAmount)`

2023-03-28 08:40 UTC, ManuGowda submitted a review, later dismissed

2023-03-28 08:53 UTC, ManuGowda approved these changes

2023-03-28 09:40 UTC, ikem-legend approved these changes

2023-03-28 09:40 UTC, ikem-legend approved these changes

2023-03-28 09:43 UTC, ManuGowda approved these changes

2023-03-28 09:43 UTC, merged