Refactor multisignature transaction creation and signing
LiskHQ/lisk-desktop pull request #4880
Opened 2023-03-27 17:01 UTC by ManuGowda

### What was the problem?

This PR resolves #4853

### How was it solved?

### How was it tested?

- [x] Token transfer (Send/Request)
- [x] Cross chain Token transfer (Send/Request)
- [x] Register Multisignature account
- [x] Reclaim tokens
- [x] Register validator
- [x] Stake/Unstake
- [x] Unlock
- [x] Claim rewards
- [x] Edit commission

2023-04-05 11:07 UTC, oskarleonard approved these changes, later dismissed

2023-04-05 14:44 UTC, ikem-legend commented
Despite fully signing a transaction from a 2 member multisig account,
<img width="747" alt="Screenshot 2023-04-05 at 15 26 52" src="https://user-images.githubusercontent.com/31376203/230116594-d4ef2c26-f21b-4c68-a537-37324857f9a2.png">\

the transaction is unable to be completed
<img width="760" alt="Screenshot 2023-04-05 at 15 23 42" src="https://user-images.githubusercontent.com/31376203/230116752-88f7b530-97d6-4114-8584-4a3eaa84234d.png">

2023-04-06 13:37 UTC, eniolam1000752 commented
Deepscan issues and PR needs merge conflicts to be resolved

2023-04-06 14:14 UTC, eniolam1000752 requested changes

2023-04-06 14:14 UTC, eniolam1000752 commented on src/modules/hardwareWallet/utils/getHWAccounts.js
> +import { getTokenBalances } from 'src/modules/account/utils/getTokenBalances';
```suggestion
import { getTokenBalances } from '@account/utils/getTokenBalances';
```

2023-04-06 14:14 UTC, eniolam1000752 commented on src/modules/token/fungible/hooks/queries/useAppsMetaTokens.js
>      params: { limit, network: 'devnet' || network, chainID, ...(customConfig?.params || {}) },
instead of having `'devent'` here we can just consume `DFAULT_NETWORK` constants which is in config.js

2023-04-08 21:07 UTC, eniolam1000752 approved these changes, later dismissed

2023-04-11 09:01 UTC, oskarleonard submitted a review, later dismissed

2023-04-11 11:07 UTC, oskarleonard approved these changes

2023-04-11 11:11 UTC, eniolam1000752 requested changes

2023-04-11 11:11 UTC, eniolam1000752 commented on src/modules/token/fungible/components/SendForm/SendForm.js
> +    const messageFee = BigInt(messageFeeResult?.data?.fee || 0) * BigInt(100000);
This hardcoded value would be changing in the future right? @ManuGowda

2023-04-11 11:11 UTC, eniolam1000752 commented on src/modules/transaction/store/actions.js
> +    ? state.account.current
I think its best to have a selector function for account something like

`selectAccount(state)`

i.e 

selectAccount = (state) =>  state.account

2023-04-11 11:22 UTC, ManuGowda commented on src/modules/token/fungible/components/SendForm/SendForm.js
> +    const messageFee = BigInt(messageFeeResult?.data?.fee || 0) * BigInt(100000);
yes

2023-04-11 11:22 UTC, ManuGowda commented on src/modules/transaction/store/actions.js
> +    ? state.account.current
for now i ll leave it like this we need to refactor bit more for hardware wallet.

2023-04-11 11:23 UTC, merged

2023-04-11 11:25 UTC, eniolam1000752 commented on src/modules/transaction/store/actions.js
> +    ? state.account.current
okay cool