WIP: replaced dashboard.path with wallet.path
LiskHQ/lisk-desktop pull request #4884
Opened 2023-03-28 12:32 UTC by oskarleonard

### What was the problem?

This PR resolves #4863

### How was it solved?

### How was it tested?

2023-03-31 09:53 UTC, ManuGowda reviewed
Remove assets or other reference related to 
- dashboard
- newsfeed

e.g setup/react/assets/images/icons/news-feed-blog-dark.svg

Also fix the button text underline for both buttons

![Screenshot 2023-03-31 at 11 40 00 AM](https://user-images.githubusercontent.com/6449871/229088264-f234e5d7-0ce4-4130-9dbb-48a7906bdcee.png)

2023-03-31 09:53 UTC, ManuGowda commented on src/modules/account/components/AccountDetails/WelcomeView/index.js
> +                key={index}
maybe start with index 1?

2023-03-31 09:53 UTC, ManuGowda commented on src/modules/auth/components/SetPasswordSuccess/SetPasswordSuccess.js
> +          {buttonText || t('Continue to account')}
```suggestion
          {buttonText || t('Continue to wallet')}
```

2023-03-31 09:53 UTC, ManuGowda commented on src/modules/auth/components/SetPasswordSuccess/SetPasswordSuccess.js
> +          {buttonText || t('Continue to account')}
For now lets keep it wallet, we need to rethink `wallet vs accounts`, until then `wallet` will be our reference

2023-03-31 09:55 UTC, ManuGowda requested changes
In general please use `wallet` as replacement for `dashboard` for now 🙏🏼

2023-03-31 09:55 UTC, ManuGowda commented on src/modules/common/components/NotFound/index.js
> +          'Sorry, we couldn’t find the page you were looking for. We suggest that you return to your account.'
```suggestion
          'Sorry, we couldn’t find the page you were looking for. We suggest that you return to your wallet.'
```

2023-03-31 09:55 UTC, ManuGowda commented on src/modules/common/components/NotFound/index.js
> +      <Link className="go-to-dashboard-button" to={routes.wallet.path}>
class names needs update?

2023-03-31 10:02 UTC, ManuGowda reviewed
![Screenshot 2023-03-31 at 11 59 20 AM](https://user-images.githubusercontent.com/6449871/229089690-9a8f761b-02ec-4ab9-ac4e-977e085f1b75.png)

When you remove all accounts, the modal show incorrect message `Continue to manage accounts`, i think just for this edge case we need to guide users stating, no accounts exists, and do it differently?

When the wallet doesn't have any accounts added, an action related to an address should be hidden, in this case, `My validator profile` or `Register validator` or `Stakes` should be hidden.

![Screenshot 2023-03-31 at 12 05 25 PM](https://user-images.githubusercontent.com/6449871/229091442-594d6c34-8b88-4d38-ab70-51e8231d546e.png)

2023-03-31 10:02 UTC, ManuGowda commented on src/modules/auth/components/SignupSuccessed/accountCreated.js
> +        'You can now add your account to Lisk Wallet by clicking on "Continue to account", to be able to send and request tokens and much more.'
```suggestion
        'You can now add your account to Lisk Wallet by clicking on "Continue". Once your account is added to wallet you will be able to send and request tokens and do much more.'
```

2023-03-31 12:21 UTC, ManuGowda approved these changes, later dismissed

2023-03-31 14:29 UTC, ManuGowda approved these changes, later dismissed

2023-03-31 14:39 UTC, ManuGowda submitted a review, later dismissed

2023-03-31 16:38 UTC, eniolam1000752 requested changes
## Review comments

- I guess this header should be sticky
![image](https://user-images.githubusercontent.com/32064769/229175781-e1c87e5b-e2a2-4d45-84a2-110fbf0a9804.png)

- Figma says line height should be 20px but it seems to be lesser 
![image](https://user-images.githubusercontent.com/32064769/229177723-4c50a6fb-bc2b-43a8-903f-bcf16ec79a0c.png)

- Figma says font size should be 32px but its 30px
![image](https://user-images.githubusercontent.com/32064769/229178184-fb5e3917-b57c-486b-8b90-00adf6228ec1.png)

- color and font size seems to be wrong
**Figma says.**  
  - Font-size: 16px.   
  - color: #70778B
  
  **Actual says**
     - Font-size: 15px
     - color: rgb(0,0,0)
 
![image](https://user-images.githubusercontent.com/32064769/229178560-58e9fc1c-d2ef-47d0-a957-2a3958c3a450.png)
   

- Figma says the border-radius should be fully rounded but actual doesn't have a fully rounded border radius
![image](https://user-images.githubusercontent.com/32064769/229178942-f2ff59c8-6b23-49e0-87ce-85a56ac87f03.png)


- Figma says font size should be 20px but actual is 32px
![image](https://user-images.githubusercontent.com/32064769/229179228-2edc44bc-e46c-4469-b5e9-abc1f22bfd62.png)

2023-04-03 10:11 UTC, eniolam1000752 approved these changes

2023-04-03 10:18 UTC, ManuGowda approved these changes

2023-04-03 10:18 UTC, merged