Retrieve off chain metadata for signing wallet connect transactions
LiskHQ/lisk-desktop pull request #4895
Opened 2023-04-10 08:06 UTC by reyraa

### What was the problem?

This PR resolves #4824

### How was it solved?

- Use `useBlockchainApplicationMeta` to retrieve and display the app data
- Use existing hooks to retrieve and pass token data

### How was it tested?

- Test manually
- Update unit tests

2023-04-11 08:27 UTC, eniolam1000752 requested changes

2023-04-11 08:27 UTC, eniolam1000752 commented on src/modules/blockchainApplication/connection/components/RequestSummary/index.js
> +    const sendingChain = metaData.data.data.find((item) => item.chainID === sendingChainID);
I would suggest that this is optional chained since during the state transition of `metaData` it could be undefined at first.

```suggestion
    const sendingChain = metaData?.data?.data?.find(({ chainID }) => chainID === sendingChainID);
```

2023-04-11 08:27 UTC, eniolam1000752 commented on src/modules/blockchainApplication/connection/components/RequestSummary/index.js
> +    const recipientChain = metaData.data.data.find((item) => item.chainID === recipientChainID);
like wise this too

```suggestion
    const recipientChain = metaData?.data?.data?.find(({ chainID }) => chainID === recipientChainID);
```

2023-04-11 08:27 UTC, eniolam1000752 commented on src/modules/blockchainApplication/connection/components/RequestSummary/index.js
> +    const token = tokenData.data.data.length > 0 ? tokenData.data.data[0] : defaultToken;
```suggestion
    const token = tokenData?.data?.data?.length > 0 ? tokenData.data.data[0] : defaultToken;
```

I would also suggest we don't do this because what I see happening here is that due to state transition of `tokenData` it would be undefined first and this would result to the UI possibly showing a wrong token symbol `LSK`. 

I would advise that until the tokenMeta and chainMeta is obtained/resolved, no symbol is shown and all actions are disabled.

2023-04-11 10:24 UTC, reyraa commented on src/modules/blockchainApplication/connection/components/RequestSummary/index.js
> +    const token = tokenData.data.data.length > 0 ? tokenData.data.data[0] : defaultToken;
Fair point. I'll apply this.

2023-04-25 08:11 UTC, ManuGowda requested changes
![Screenshot 2023-04-25 at 10 09 11 AM](https://user-images.githubusercontent.com/6449871/234215315-2b6f9e52-3d09-4071-8dfa-c8077dbe57a9.png)
![Screenshot 2023-04-25 at 10 09 57 AM](https://user-images.githubusercontent.com/6449871/234215320-89e2849c-1da2-4e28-b3cb-eabe82e82722.png)
![Screenshot 2023-04-25 at 10 10 27 AM](https://user-images.githubusercontent.com/6449871/234215327-282e4b50-f898-4740-bd54-d41c7bf2e80f.png)

2023-04-25 08:49 UTC, eniolam1000752 requested changes
### Ui comments

- Padding doesn't look right on small and medium screens
![image](https://user-images.githubusercontent.com/32064769/234219239-ddaa5bd2-7c21-42e3-9671-d7c06aaf68cc.png)

- Active account checkmark seems to be too close to the checkbox of the other account at its side
![image](https://user-images.githubusercontent.com/32064769/234220582-daafc172-c048-4d43-a614-4be0b27aa934.png)

- Application breaks on trying to sign request transaction signing
![image](https://user-images.githubusercontent.com/32064769/234224156-1bb90a73-adc8-46f9-95ac-bcef17f1e63e.png)

-

2023-04-25 15:20 UTC, oskarleonard commented on libs/wcm/hooks/useSession.js
> +      setSessionProposal(null);
This part looks a bit strange? Calling the same function twice in the same scope, and also one time with `await` and the other call doesn't use `await`

2023-04-26 07:24 UTC, reyraa commented on libs/wcm/hooks/useSession.js
> +      setSessionProposal(null);
Resolved

2023-04-26 07:56 UTC, ManuGowda approved these changes

2023-04-26 07:56 UTC, eniolam1000752 approved these changes

2023-04-26 07:56 UTC, merged