Resolve transactions event update issue
LiskHQ/lisk-desktop pull request #4931
Opened 2023-04-21 11:10 UTC by eniolam1000752

### What was the problem?

This PR resolves #4930

### How was it solved?

- [x] Added client.socket dependency to useEffect on useTransctionUpdate

### How was it tested?

- Visually
- Jest

2023-04-21 11:11 UTC, ikem-legend commented on src/utils/api/client.js
> +      console.log('===', `${ws}/blockchain`);
@eniolam1000752 Please remove this log

2023-04-21 13:42 UTC, oskarleonard commented on setup/react/app/ApplicationBootstrap.js
> +  useTransactionUpdate();
Why did we move this one? Feels cleaner if all hooks are at the same place if they arent dependent on some variable, and we dont seem to pass in `mainChainApplication`, `isError`, nor `isLoading` to this hook

2023-04-21 13:42 UTC, oskarleonard approved these changes, later dismissed

2023-04-21 14:09 UTC, ikem-legend submitted a review, later dismissed

2023-04-21 15:15 UTC, ManuGowda requested changes
On sending tokens i see duplicate rows for same information

<img width="1362" alt="Screenshot 2023-04-21 at 5 14 16 PM" src="https://user-images.githubusercontent.com/6449871/233672785-10317485-c917-422a-ae0c-064f0e57f70f.png">


It should show only one row

2023-04-24 06:06 UTC, ManuGowda approved these changes

2023-04-24 08:09 UTC, oskarleonard approved these changes

2023-04-24 08:41 UTC, merged