Fix scroll issue with confirmation button on small screens
LiskHQ/lisk-desktop pull request #4988
Opened 2023-05-10 12:22 UTC by ikem-legend

### What was the problem?

This PR resolves #3893

### How was it solved?

- Adding scroll to the styling for the pages

### How was it tested?

- Visually

2023-05-10 15:31 UTC, ManuGowda requested changes
Please observe the same issues on other transactions as well

1. Register validator
2. Unlock
3. Vote
4. Claim Rewards

In general this problem can exists on all types of transaction views

2023-05-11 08:50 UTC, eniolam1000752 requested changes

2023-05-11 08:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/RegisterValidatorView/registerValidator.css
> +  overflow: scroll;
Instead of `scroll` lets use `auto` so that on windows we don't have a scroll bar taking up space when there isn't any overflow

2023-05-11 08:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/UnlockBalanceView/styles.css
> +  overflow: scroll;
likewise here, we can use `auto`

2023-05-11 08:50 UTC, eniolam1000752 commented on src/modules/token/fungible/components/SendForm/form.css
> +  overflow-y: scroll;
likewise here, we can use `auto`

2023-05-11 08:50 UTC, eniolam1000752 commented on src/modules/wallet/components/RegisterMultisigForm/styles.css
> +  overflow: scroll;
likewise here, we can use `auto`

2023-05-11 08:50 UTC, eniolam1000752 commented on src/modules/wallet/components/RegisterMultisigView/styles.css
> +  overflow: scroll;
likewise here, we can use `auto`

2023-05-11 12:19 UTC, ManuGowda approved these changes

2023-05-11 12:20 UTC, oskarleonard approved these changes

2023-05-11 12:23 UTC, merged