Design fixes claim rewards unlock stakes
LiskHQ/lisk-desktop pull request #5001
Opened 2023-05-16 14:31 UTC by oskarleonard

### What was the problem?

This PR resolves #4757

### How was it solved?

Just adjusting a small ui fixe and scrollbar fix

### How was it tested?

Manually

2023-05-17 09:18 UTC, ikem-legend approved these changes, later dismissed

2023-05-22 08:44 UTC, eniolam1000752 requested changes

2023-05-22 08:44 UTC, eniolam1000752 commented on src/modules/pos/validator/components/StakeSuccessfulModal/StakeSuccessfulModal.test.js
> +      expect(props.history.push).toHaveBeenCalledWith('/validators/profile/stakes');
```suggestion
      expect(props.history.push).toHaveBeenCalledWith(routes.sentStakes.path);
```

2023-05-22 09:09 UTC, oskarleonard commented on src/modules/pos/validator/components/StakeSuccessfulModal/StakeSuccessfulModal.test.js
> +      expect(props.history.push).toHaveBeenCalledWith('/validators/profile/stakes');
Fixed https://github.com/LiskHQ/lisk-desktop/pull/5001/commits/785a7e7e18589a5c596bf7b2cf6e3a3eb61db188

2023-05-22 09:40 UTC, ikem-legend approved these changes

2023-05-22 10:16 UTC, eniolam1000752 approved these changes

2023-05-22 10:23 UTC, merged