Fix status and peer list rending issues
LiskHQ/lisk-desktop pull request #5011
Opened 2023-05-19 11:00 UTC by ManuGowda

### What was the problem?

This PR resolves #5010 and #5006

### How was it solved?

- Use correct property name exposed by API

### How was it tested?

Visually and Update unit tests

2023-05-19 17:02 UTC, ikem-legend reviewed
Looks good. Just a minor change

2023-05-19 17:02 UTC, ikem-legend commented on src/theme/Icon/index.js
> +import inprogress from '@setup/react/assets/images/icons/inprogress.svg';
@ManuGowda Please use camel case for icon names

2023-05-19 17:02 UTC, ikem-legend reviewed
Looks good. Just a minor change

2023-05-22 07:59 UTC, eniolam1000752 requested changes
Sort by latest block height for a network node seems to be bugged.

When I sort in ascending order, at the bottom, I see that `Unknown` comes before a block height which is lesser that the height just above the `Unknown` value

![image](https://github.com/LiskHQ/lisk-desktop/assets/32064769/7eefcbf9-cbe0-4662-9b3c-2d1e1867276d)

2023-05-22 10:08 UTC, oskarleonard submitted a review, later dismissed

2023-05-22 10:48 UTC, eniolam1000752 approved these changes, later dismissed

2023-05-22 10:57 UTC, ikem-legend submitted a review, later dismissed

2023-05-22 11:17 UTC, ikem-legend approved these changes

2023-05-22 11:26 UTC, eniolam1000752 approved these changes

2023-05-22 11:26 UTC, merged