Resolve distorted UI issues
LiskHQ/lisk-desktop pull request #5061
Opened 2023-06-01 09:18 UTC by ManuGowda

### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

### How was it tested?

2023-06-05 14:27 UTC, ManuGowda reviewed
<img width="758" alt="Screenshot 2023-06-05 at 4 27 07 PM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/9840b375-3adb-4fc6-9fd6-8403548414c8">

for generic case, the pretty JSON should be rendered properly

2023-06-06 09:56 UTC, eniolam1000752 requested changes
## UI comments

- For a cross chain token transfer, I think it would be cool if the summary shows recipient chain and its log
<img width="733" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/76b4aa78-e756-4871-a1c7-77699f99718d">

2023-06-06 09:56 UTC, eniolam1000752 commented on src/modules/blockchainApplication/manage/components/RemoveApplicationSuccess/RemoveApplicationSuccess.js
> +        <PrimaryButton className={`${styles.button}`} onClick={onRemoveSuccess}>
```suggestion
        <PrimaryButton className={styles.button} onClick={onRemoveSuccess}>
```

2023-06-06 10:52 UTC, ikem-legend commented on src/modules/blockchainApplication/manage/components/RemoveApplicationSuccess/RemoveApplicationSuccess.js
> +        <PrimaryButton className={`${styles.button}`} onClick={onRemoveSuccess}>
Done

2023-06-06 11:45 UTC, eniolam1000752 approved these changes

2023-06-06 11:47 UTC, ikem-legend commented on src/modules/transaction/components/TransactionDetails/messageFee.js
> +const Fee = ({ t }) => {
This should be renamed to MessageFee

2023-06-06 11:47 UTC, ikem-legend approved these changes
Looks good to me. Added a minor comment

2023-06-06 11:47 UTC, merged