Fix horizontal scrollbar bug in modals
LiskHQ/lisk-desktop pull request #5084
Opened 2023-06-13 12:59 UTC by ikem-legend

### What was the problem?

This PR resolves #5032

### How was it solved?

- Updating the styling for the different transaction modals

### How was it tested?

Visually

2023-06-13 15:08 UTC, eniolam1000752 requested changes
Should the Dialog component its self benefit from not having a horizontal scroll. 

This is so that other uses cased of the component don't suffer from an horizontal scroll.

2023-06-13 15:30 UTC, ikem-legend commented
> Should the Dialog component its self benefit from not having a horizontal scroll.
> 
> This is so that other uses cased of the component don't suffer from an horizontal scroll.

I considered doing so but was uncertain about if that might possibly create problems in some other views

2023-06-14 12:40 UTC, eniolam1000752 approved these changes, later dismissed

2023-06-14 12:50 UTC, oskarleonard commented on src/modules/pos/validator/components/RegisterValidatorView/index.js
>    }, []);
NRTTL found some more
![image](https://github.com/LiskHQ/lisk-desktop/assets/8784876/99b12802-2191-4cdb-9a16-3fde2ef2703b)
![image](https://github.com/LiskHQ/lisk-desktop/assets/8784876/c123d329-200f-4104-97ff-eee4f3204881)

I think we should do as we discussed in slack some time ago, this problem got introduced in https://github.com/LiskHQ/lisk-desktop/pull/4988 if my memory serves me correctly, which is caused by children inside children both having scroll overflow

2023-06-14 18:39 UTC, eniolam1000752 approved these changes

2023-06-14 18:48 UTC, ikem-legend commented on src/modules/pos/validator/components/RegisterValidatorView/index.js
>    }, []);
Fixed

2023-06-15 08:17 UTC, ManuGowda approved these changes
Tested on mac works fine (couldn't test unlock and claim rewards)

2023-06-15 08:17 UTC, merged