Incorrect unlock times
LiskHQ/lisk-desktop pull request #5086
Opened 2023-06-13 16:10 UTC by oskarleonard

### What was the problem?

This PR resolves #5049

### How was it solved?

Use the `expectedUnlockTime` field from BE to determine when a stake can be unlocked

### How to test?

1. Stake 100 with a validator
2. Edit that stake to 80
3. Go to http://0.0.0.0:8080/#/validators/profile/stakes?modal=lockedBalance
4. You should see a text with "20 LSK" - "will be available to unlock in a month"

2023-06-14 05:51 UTC, ManuGowda reviewed
<img width="497" alt="Screenshot 2023-06-14 at 7 48 16 AM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/62465c7e-3453-4655-854d-aa8f53f68aa8">

src/modules/pos/validator/components/StakeStatus/statusMessages.js

This is part of the logic that needs refactoring.

2023-06-14 13:50 UTC, ManuGowda commented on src/modules/pos/validator/components/StakeStatus/statusMessages.js
> +            <span>{t('Your tokens will be available to unlock when the locking period ends')}</span>
when the locking period ends.

2023-06-14 13:50 UTC, ManuGowda commented on src/modules/pos/validator/components/StakeStatus/statusMessages.js
> +            <span>{t('Your tokens will be available to unlock when the locking period ends')}</span>
when the locking period ends.

2023-06-14 13:50 UTC, ManuGowda commented on src/modules/pos/validator/components/StakeStatus/statusMessages.js
> +        <span>{t('when the locking period ends,')}</span>
when the locking period ends.

2023-06-14 14:02 UTC, ManuGowda requested changes
<img width="742" alt="Screenshot 2023-06-14 at 4 01 59 PM" src="https://github.com/LiskHQ/lisk-desktop/assets/6449871/bf3a2a6e-a9de-4459-a570-0b5895c5a332">

Need to handle the invalid date case

2023-06-14 16:48 UTC, ManuGowda approved these changes

2023-06-15 08:09 UTC, ikem-legend approved these changes

2023-06-15 08:28 UTC, merged