4999 integrate tx fee endpoint
LiskHQ/lisk-desktop pull request #5094
Opened 2023-06-16 14:21 UTC by eniolam1000752

### What was the problem?

This PR resolves #49999

### How was it solved?

- [x] Implement `useTransactionEstimateFees` hook
- [ ] consume `useTransactionEstimateFees` into useTransactionFee hook
- [ ] Fix unit tests

### How was it tested?

- JEST
- Visually

2023-08-09 07:37 UTC, ManuGowda commented on src/modules/auth/components/EnterPasswordForm/decryptAccountWorker.js
> +import { decryptAccount } from '../../../account/utils';
follow same file name convention `decryptAccount.worker.js`

2023-08-09 07:37 UTC, ManuGowda commented on src/modules/auth/components/EnterPasswordForm/decryptAccountWorker.test.js
> +import { decryptAccount } from '../../../account/utils';
same update the file name

2023-08-09 07:37 UTC, ManuGowda commented on src/modules/transaction/components/TxComposer/index.js
> +  } = useTransactionFee({
Call fee hook once all the required form fields are available. Check delegate registration transaction, without entering the keys its triggering the hook

2023-08-09 07:37 UTC, ManuGowda commented on src/modules/transaction/hooks/useTransactionFee/useTransactionFee.js
> +    moduleCommand !== 'token:transferCrossChain' &&
use the map MODULE_COMMANDS_NAME_MAP.transfer , MODULE_COMMANDS_NAME_MAP.transferCrossChain?

2023-08-09 08:35 UTC, ManuGowda reviewed
Show feedback on form which doesn't have enough balance to complete the transaction.

STR:
- have 0.1 balance on wallet
- initiate register multisignature/register validator/staking
- check the user has not received any feedback

2023-08-10 12:04 UTC, oskarleonard commented on src/modules/transaction/components/TxComposer/index.js
> +import { dryRun } from '../../api';
can we use alias for these?

2023-08-10 12:08 UTC, ManuGowda requested changes
for fee estimate can we trigger the estimate endpoint once onBlur? so that we do not have api calls until the input is complete?
ex.  a user can type 64 char for message and we are calling the endpoint 64 times :disappointed: so its not optimised.. same applies for amount or any other field which needs blur implementation.

2023-08-10 13:48 UTC, ManuGowda approved these changes

2023-08-10 13:51 UTC, oskarleonard approved these changes

2023-08-10 13:52 UTC, merged