Implement edit and remove custom network
LiskHQ/lisk-desktop pull request #5095
Opened 2023-06-19 17:00 UTC by ikem-legend

### What was the problem?

This PR resolves #5031

### How was it solved?

- [x] Implement edit functionality
- [ ] Implement remove functionality

### How was it tested?

- Unit tests

2023-06-21 07:32 UTC, ManuGowda requested changes
- We should not provide the delete option when its current selected network? only edit network is feasible?
![Screenshot 2023-06-21 at 9 20 18 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/5ac9d1fd-c1f1-438a-954e-59c82e82bbfa)

- We are not pinging the service URL to check if its a valid mainchain URL? it will simply add any valid formate URL? which is wrong? After we receive the service URL input we should ping and check if its a valid mainchain URL and then add it and if its invalid we should give error and not allow to add it.
![Screenshot 2023-06-21 at 9 20 58 AM](https://github.com/LiskHQ/lisk-desktop/assets/6449871/13aa8435-7100-4753-96e1-82574506fb61)

2023-06-21 07:32 UTC, ManuGowda commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +                pattern: { value: regex.networkName, message: t('Invalid Network Name') },
```suggestion
                pattern: { value: regex.networkName, message: t('Invalid network name') },
```

2023-06-21 07:32 UTC, ManuGowda commented on src/modules/network/components/DialogRemoveNetwork/DialogRemoveNetwork.js
> +                Cancel remove
Missing translation?

2023-06-21 07:32 UTC, ManuGowda commented on src/modules/network/components/DialogRemoveNetwork/DialogRemoveNetwork.js
> +      toast.info(`Network removed "${name}"`, { position: 'bottom-right' });
translation?

2023-06-21 08:53 UTC, ikem-legend commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +                pattern: { value: regex.networkName, message: t('Invalid Network Name') },
Fixed

2023-06-21 08:53 UTC, ikem-legend commented on src/modules/network/components/DialogRemoveNetwork/DialogRemoveNetwork.js
> +      toast.info(`Network removed "${name}"`, { position: 'bottom-right' });
Fixed

2023-06-21 08:53 UTC, ikem-legend commented on src/modules/network/components/DialogRemoveNetwork/DialogRemoveNetwork.js
> +                Cancel remove
Fixed

2023-06-23 10:33 UTC, ManuGowda submitted a review, later dismissed

2023-06-26 08:10 UTC, eniolam1000752 requested changes
UI/UX issues observed

- there is a bouncy effect observed when you try to over between custom networks. I guess this is as a result of the deleted/edit icon's height interfering with the overall height.
<img width="697" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/ddbd3132-bcbc-45a1-a2f9-ce15a123fe18">

- The edit and delete icons shows when I hover on the selected network
<img width="690" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/825bd631-fb4f-4b3d-8ec0-c94e4db56e2c">


- It seems we aren't doing a network status check on adding a network.

2023-06-26 08:29 UTC, eniolam1000752 commented
> UI/UX issues observed
> 
> * there is a bouncy effect observed when you try to over between custom networks. I guess this is as a result of the deleted/edit icon's height interfering with the overall height.
> 
> <img alt="image" width="697" src="https://user-images.githubusercontent.com/32064769/248725759-ddbd3132-bcbc-45a1-a2f9-ce15a123fe18.png">
> * The edit and delete icons shows when I hover on the selected network
> 
> <img alt="image" width="690" src="https://user-images.githubusercontent.com/32064769/248726362-825bd631-fb4f-4b3d-8ec0-c94e4db56e2c.png">
> * It seems we aren't doing a network status check on adding a network.

I guess you can discard my second and third comment :)

2023-06-26 08:36 UTC, oskarleonard commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +  const mode = defaultName ? 'edit' : 'add';
We are adding complexity with this extra variable, meaning this component can easily be using two different logic for the same thing (as we can already see where we do `if (defaultName) {`)

One logic like this would be cleaner imo  `{!!defaultName ? <edit> : <add>}`

2023-06-26 08:49 UTC, oskarleonard commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +    if (mode === 'add' && (existingCustomNetworkName || existingCustomNetworkServiceUrl)) {
We dont need `mode === 'add'` here

2023-06-26 09:03 UTC, ikem-legend commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +    if (mode === 'add' && (existingCustomNetworkName || existingCustomNetworkServiceUrl)) {
Fixed

2023-06-26 09:03 UTC, oskarleonard approved these changes

2023-06-26 09:03 UTC, ikem-legend commented on src/modules/network/components/DialogAddNetwork/DialogAddNetwork.js
> +  const mode = defaultName ? 'edit' : 'add';
Fixed

2023-06-26 09:15 UTC, eniolam1000752 approved these changes

2023-06-26 09:15 UTC, ManuGowda approved these changes

2023-06-26 09:15 UTC, merged