Lisk-desktop: modal screen leads to crash
LiskHQ/lisk-desktop pull request #5206
Opened 2023-07-25 13:43 UTC by ManuGowda

### What was the problem?

This PR resolves #5195 

### How was it solved?

- :bug: Fix modal crash by handling the required search params 

### How was it tested?

2023-07-31 21:12 UTC, eniolam1000752 requested changes
## Review comments

I think the following modal routes needs the following search params to be required 

- `removeApplicationFlow`: search params -> `chainId`
- `blockChainApplicationDetails` : search params -> `chainId`

2023-08-01 13:28 UTC, oskarleonard submitted a review, later dismissed

2023-08-02 08:53 UTC, oskarleonard approved these changes

2023-08-02 11:53 UTC, eniolam1000752 approved these changes

2023-08-02 11:53 UTC, merged