Incorrect js docs
LiskHQ/lisk-desktop pull request #5221
Opened 2023-08-02 13:32 UTC by oskarleonard

### What was the problem?

This PR resolves #5190

### How was it solved?

Removed most of our Js docs since much of it is deprecated and difficult to have up to date. Future focus will be to have self documented code with type script.

### How was it tested?

Manually

2023-08-02 17:41 UTC, ManuGowda commented on src/modules/pos/validator/store/actions/staking.js
> + * The reducer will add a new stake if i didn't exist before
```suggestion
 * The reducer will add a new stake if it didn't exist before
```

2023-08-02 17:41 UTC, ManuGowda approved these changes, later dismissed

2023-08-03 08:35 UTC, ManuGowda approved these changes

2023-08-03 13:35 UTC, eniolam1000752 requested changes

2023-08-03 13:35 UTC, eniolam1000752 commented on src/modules/auth/store/action.js
> - * Store second passphrase in the Redux store
I think we can still retain this line

2023-08-03 13:35 UTC, eniolam1000752 commented on src/modules/auth/store/action.js
> - * Removes the second passphrase from the Redux store
can 't we also retain this

2023-08-03 13:35 UTC, eniolam1000752 commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js
> - * Creates a custom hook for blockchain applications list queries
can't we retain this

2023-08-03 13:35 UTC, eniolam1000752 commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationStatistics.js
> - * Creates a custom hook for blockchain applications meta queries
can't we retain this too

2023-08-03 15:01 UTC, oskarleonard commented on src/modules/auth/store/action.js
> - * Store second passphrase in the Redux store
To me all of these descriptions are redundant.
Imo, it is better to have self documenting code, which for these cases i feel that we have.
File is in a folder called /store (so i interpret redux) and the file is called action (so i interpret functions here modifies the redux state).

How do you feel the comment brings value?

I guess `setSecondPassphrase` would have been a better name, but still `secondPassphraseStored` is understandable.

2023-08-03 15:03 UTC, oskarleonard commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js
> - * Creates a custom hook for blockchain applications list queries
But we agreed that we should remove all this params because too many docs in the code base have incorrect values. I think it gives a false sense of security, better to just look up swagger when i need to know what parameters i can send

2023-08-03 15:07 UTC, oskarleonard commented on src/modules/blockchainApplication/explore/hooks/queries/useBlockchainApplicationExplore.js
> - * Creates a custom hook for blockchain applications list queries
Feels strange to leave it in some places and remove it in other places is mostly my concern :/

2023-08-03 17:01 UTC, eniolam1000752 approved these changes

2023-08-03 17:01 UTC, merged