Implement account details view
LiskHQ/lisk-desktop pull request #5259
Opened 2023-08-17 16:35 UTC by ikem-legend

### What was the problem?

This PR resolves #5238

### How was it solved?

- [ ] Update account menu
- [ ] Implement account details UI

### How was it tested?

- Visually
- Unit tests

2023-08-23 14:38 UTC, eniolam1000752 requested changes
## Ui issues observed

- The tooltip is clipped due tot he overflow on the section
<img width="592" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/e3bf164d-5082-415f-b041-9a315e0bdbca">

- There is suppose to be a padding of 8px in the highlighted space
<img width="405" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/d23f1de9-4d76-4ed0-b57f-37170384754f">

-

2023-08-23 14:38 UTC, eniolam1000752 commented on src/modules/wallet/components/AccountDetails/index.js
> +    setError,
```suggestion
    formState: { errors, isDirty },
    setValue,
    setError,
    formState: { errors, isDirty },
```

2023-08-23 14:53 UTC, ManuGowda commented on src/modules/wallet/components/AccountDetails/index.js
> +  const queryAddress = selectSearchParamValue(history.location.search, 'validatorAddress');
```suggestion
  const queryAddress = selectSearchParamValue(history.location.search, 'validatorAddress') || selectSearchParamValue(history.location.search, 'address');
```

2023-08-23 14:53 UTC, ManuGowda commented on src/modules/wallet/components/AccountDetails/index.js
> +                  text={truncateAddress(publicKey)}
```suggestion
                  value={publicKey || currentAccount.metadata.pubkey}
                  className={styles.rowValue}
                  text={truncateAddress(publicKey || currentAccount.metadata.pubkey)}
```

2023-08-23 15:57 UTC, ikem-legend commented on src/modules/wallet/components/AccountDetails/index.js
> +    setError,
Fixed

2023-08-23 15:57 UTC, ikem-legend commented on src/modules/wallet/components/AccountDetails/index.js
> +                  text={truncateAddress(publicKey)}
Fixed

2023-08-23 17:43 UTC, ManuGowda approved these changes, later dismissed

2023-08-23 19:40 UTC, eniolam1000752 requested changes
There is just one minor issue, The page goes blank when there are more than 4 signatories to the account
<img width="1397" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/cd13ed33-0c93-4621-835a-15458b527f60">

2023-08-24 13:08 UTC, eniolam1000752 approved these changes

2023-08-24 13:35 UTC, Balanced02 approved these changes

2023-08-24 13:35 UTC, merged