:bug: Fix timestamp calculation
LiskHQ/lisk-desktop pull request #5268
Opened 2023-08-28 08:21 UTC by ManuGowda

### What was the problem?

This PR resolves #5266 

### How was it solved?

- Fix last forger timestamp calculation

### How was it tested?

- view validators tab and go over some validator profile and check the last forged timestamp

2023-08-28 09:10 UTC, oskarleonard approved these changes, later dismissed

2023-08-28 09:50 UTC, eniolam1000752 requested changes

2023-08-28 09:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/ValidatorProfile/DetailsView.js
> +    options: { enable: !lastGeneratedHeight },
Shouldn't this be

```
!!lastGeneratedHeight
```

2023-08-28 09:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/ValidatorProfile/DetailsView.js
> +  const { data: generateBlock } = useBlocks({
```suggestion
  const { data: generatedBlock } = useBlocks({
```

2023-08-28 09:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/ValidatorProfile/DetailsView.js
> +      value: generateBlock?.data?.[0] ? (
```suggestion
      value: generatedBlock?.data?.[0] ? (
```

2023-08-28 09:50 UTC, eniolam1000752 commented on src/modules/pos/validator/components/ValidatorProfile/DetailsView.js
> +          time={generateBlock?.data?.[0].timestamp}
```suggestion
          time={generatedBlock?.data?.[0].timestamp}
```

2023-08-28 19:58 UTC, eniolam1000752 approved these changes, later dismissed

2023-08-29 04:56 UTC, ikem-legend commented on src/modules/pos/validator/components/ValidatorProfile/DetailsView.js
> +    options: { enable: !!lastGeneratedHeight },
Typo here. Should be `enabled`

2023-08-29 07:46 UTC, ikem-legend approved these changes, later dismissed

2023-08-29 07:50 UTC, oskarleonard approved these changes

2023-08-29 07:50 UTC, ikem-legend approved these changes

2023-08-29 07:51 UTC, eniolam1000752 approved these changes

2023-08-29 08:23 UTC, merged