Fix windows testing feedback issues
LiskHQ/lisk-desktop pull request #5281
Opened 2023-08-30 16:02 UTC by ikem-legend

### What was the problem?

This PR resolves #5225

### How was it solved?

- [x] Fixed create account board scroll
- [x] Fixed passphrase confirmations options display logic
- [x] Updating redirect on account creation

### How was it tested?

- Manually

2023-08-30 18:18 UTC, ManuGowda reviewed
The request link issue is not resolved?

2023-09-01 13:12 UTC, ManuGowda approved these changes, later dismissed

2023-09-01 13:25 UTC, eniolam1000752 requested changes

2023-09-01 13:25 UTC, eniolam1000752 commented on src/modules/auth/components/ConfirmPassphrase/confirmPassphrase.test.js
> +    });
```suggestion
    await waitFor(selectRightWords);
```

2023-09-01 13:33 UTC, ManuGowda approved these changes

2023-09-01 13:35 UTC, eniolam1000752 approved these changes

2023-09-01 13:35 UTC, merged