Bugfix account balance calculation
LiskHQ/lisk-desktop pull request #5356
Opened 2023-10-02 12:14 UTC by ManuGowda

### What was the problem?

This PR resolves #5349

### How was it solved?

### How was it tested?

2023-10-02 15:27 UTC, eniolam1000752 submitted a review, later dismissed

2023-10-03 15:19 UTC, ikem-legend commented on src/modules/transaction/api/index.js
> +      : TOKEN_EVENT_DATA_RESULT[event.data.result];
There are also errors tied to other module commands like staking. So maybe a case statement might be the best solution for this case

2023-10-04 07:15 UTC, eniolam1000752 requested changes

2023-10-04 07:15 UTC, eniolam1000752 commented on src/modules/transaction/constants.js
> +};
This constant wasn't consumed anywhere else

2023-10-04 08:42 UTC, ikem-legend commented on src/modules/transaction/api/index.js
> +        return TOKEN_EVENT_DATA_RESULT[event.data.result];
Should be `return POS_EVENT_DATA_RESULT[event.data.result]`

2023-10-04 08:44 UTC, ikem-legend approved these changes

2023-10-04 09:12 UTC, eniolam1000752 approved these changes

2023-10-04 09:13 UTC, merged