Prevent auto update of generator table
LiskHQ/lisk-desktop pull request #5422
Opened 2023-11-08 14:21 UTC by oskarleonard

### What was the problem?

This PR resolves #5399

### How was it solved?

Replacing refetchInterval on generator table with ui button to enable refreshes of this table.

### How was it tested?

1. Go to http://localhost:8080/#/validators
2. Sort by commission
3. Wait 20 sec
4. Expected: List should not have been update
5. Click Refresh
6. Expected: List is now updated

2023-11-08 15:39 UTC, eniolam1000752 requested changes
- I get this error when I navigate to  other tabs like`Validators` and `Sanctioned` tab.

<img width="1675" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/cca98a79-a7a2-49c0-a771-61461500d172">

- Placement seems disturbing as it distorts the view of the other tabs
<img width="757" alt="image" src="https://github.com/LiskHQ/lisk-desktop/assets/32064769/9da86abc-0b7a-4a76-b00b-1c88a4e8269b">

2023-11-08 15:39 UTC, eniolam1000752 commented on src/theme/QueryTable/QueryTable.js
> +      document.querySelector(`.${styles.header}`)?.getBoundingClientRect().top - window.scrollY <=
```suggestion
      (document.querySelector(`.${styles.header}`)?.getBoundingClientRect()?.top || window.scrollY) - window.scrollY <=
```

2023-11-09 11:17 UTC, ikem-legend approved these changes

2023-11-09 11:17 UTC, eniolam1000752 approved these changes

2023-11-09 11:18 UTC, merged