Add final mainnet balance
LiskHQ/lisk-desktop pull request #5597
Opened 2024-07-30 14:11 UTC by ikem-legend

### What was the problem?

This PR resolves #5596

### How was it solved?

- Add final balance
- Remove Request / Send / view all tokens button
- Remove Transactions / Events tabs
- Add Download Account History button

### How was it tested?

- Unit test

2024-07-30 21:25 UTC, shuse2 requested changes
* Token claim on the testnet is not working, (also good to check mainnet too)
```
Invalid signature request initiated from another application/network.
Please switch application/network to selected value during connection initialization
```
* For mainnet, if we connect with the address without balance, it shows error. (on mainnet or testnet). Can we show `0` balance instead?
* For testnet, it shows network error. Can we show `0` or `unknown`?
* Can we hide the history button on testnet?

2024-08-01 07:26 UTC, shuse2 commented
When i changed to testnet, i had attached error.
![Screenshot 2024-08-01 at 09 23 58](https://github.com/user-attachments/assets/93e96a58-5ad5-4282-8088-9ea21db164b6)
Also, `wallet` page is not shown anywhere, i think we should bring it back?

2024-08-09 15:41 UTC, shuse2 submitted a review, later dismissed

2024-08-12 10:35 UTC, clemente-xyz approved these changes

2024-08-12 11:45 UTC, shuse2 approved these changes

2024-08-12 11:45 UTC, merged